//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	/// <summary>
	/// Represents a runtime instance of a user's milestone status. Live Milestone data should be combined with DestinyMilestoneDefinition data to show the user a picture of what is available for them to do in the game, and their status in regards to said "things to do." Consider it a big, wonky to-do list, or Advisors 3.0 for those who remember the Destiny 1 API.
	/// </summary>
	public partial class DestinyMilestone
	{
		[JsonProperty("milestoneHash")]
		public uint MilestoneHash { get; set; }

		[JsonProperty("availableQuests")]
		public Destiny.Milestones.DestinyMilestoneQuest[] AvailableQuests { get; set; }

		[JsonProperty("activities")]
		public Destiny.Milestones.DestinyMilestoneChallengeActivity[] Activities { get; set; }

		[JsonProperty("values")]
		public System.Collections.Generic.Dictionary<string, decimal> Values { get; set; }

		[JsonProperty("vendorHashes")]
		public uint[] VendorHashes { get; set; }

		[JsonProperty("vendors")]
		public Destiny.Milestones.DestinyMilestoneVendor[] Vendors { get; set; }

		[JsonProperty("rewards")]
		public Destiny.Milestones.DestinyMilestoneRewardCategory[] Rewards { get; set; }

		[JsonProperty("startDate")]
		public DateTime? StartDate { get; set; }

		[JsonProperty("endDate")]
		public DateTime? EndDate { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }
	}
}
