//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	public partial class DestinyPublicMilestoneChallengeActivity
	{
		[JsonProperty("activityHash")]
		public uint ActivityHash { get; set; }

		[JsonProperty("challengeObjectiveHashes")]
		public uint[] ChallengeObjectiveHashes { get; set; }

		[JsonProperty("modifierHashes")]
		public uint[] ModifierHashes { get; set; }

		[JsonProperty("loadoutRequirementIndex")]
		public int? LoadoutRequirementIndex { get; set; }

		[JsonProperty("phaseHashes")]
		public uint[] PhaseHashes { get; set; }

		[JsonProperty("booleanActivityOptions")]
		public System.Collections.Generic.Dictionary<uint, bool> BooleanActivityOptions { get; set; }
	}
}
