//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	public partial class DestinyPublicMilestoneVendor
	{
		[JsonProperty("vendorHash")]
		public uint VendorHash { get; set; }

		[JsonProperty("previewItemHash")]
		public uint? PreviewItemHash { get; set; }
	}
}
