//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	/// <summary>
	/// Information about milestones, presented in a character state-agnostic manner. Combine this data with DestinyMilestoneDefinition to get a full picture of the milestone, which is basically a checklist of things to do in the game. Think of this as GetPublicAdvisors 3.0, for those who used the Destiny 1 API.
	/// </summary>
	public partial class DestinyPublicMilestone
	{
		[JsonProperty("milestoneHash")]
		public uint MilestoneHash { get; set; }

		[JsonProperty("availableQuests")]
		public Destiny.Milestones.DestinyPublicMilestoneQuest[] AvailableQuests { get; set; }

		[JsonProperty("activities")]
		public Destiny.Milestones.DestinyPublicMilestoneChallengeActivity[] Activities { get; set; }

		[JsonProperty("vendorHashes")]
		public uint[] VendorHashes { get; set; }

		[JsonProperty("vendors")]
		public Destiny.Milestones.DestinyPublicMilestoneVendor[] Vendors { get; set; }

		[JsonProperty("startDate")]
		public DateTime? StartDate { get; set; }

		[JsonProperty("endDate")]
		public DateTime? EndDate { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }
	}
}
