//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	/// <summary>
	/// Represents this player's personal completion status for the Activity under a Milestone, if the activity has trackable completion and progress information. (most activities won't, or the concept won't apply. For instance, it makes sense to talk about a tier of a raid as being Completed or having progress, but it doesn't make sense to talk about a Crucible Playlist in those terms.
	/// </summary>
	public partial class DestinyMilestoneActivityCompletionStatus
	{
		[JsonProperty("completed")]
		public bool Completed { get; set; }

		[JsonProperty("phases")]
		public Destiny.Milestones.DestinyMilestoneActivityPhase[] Phases { get; set; }
	}
}
