// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	/// <summary>
	/// Represents a category of "summary" rewards that can be earned for the Milestone regardless of specific quest rewards that can be earned.
	/// </summary>
	public partial class DestinyMilestoneRewardCategory
	{
		[JsonProperty("rewardCategoryHash")]
		public uint RewardCategoryHash { get; set; }

		[JsonProperty("entries")]
		public Destiny.Milestones.DestinyMilestoneRewardEntry[] Entries { get; set; }
	}
}
