// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	public partial class DestinyMilestoneChallengeActivity
	{
		[JsonProperty("activityHash")]
		public uint ActivityHash { get; set; }

		[JsonProperty("challenges")]
		public Destiny.Challenges.DestinyChallengeStatus[] Challenges { get; set; }

		[JsonProperty("modifierHashes")]
		public uint[] ModifierHashes { get; set; }

		[JsonProperty("loadoutRequirementIndex")]
		public int? LoadoutRequirementIndex { get; set; }

		[JsonProperty("phases")]
		public Destiny.Milestones.DestinyMilestoneActivityPhase[] Phases { get; set; }
	}
}
