//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Milestones
{
	/// <summary>
	/// The character-specific data for a milestone's reward entry. See DestinyMilestoneDefinition for more information about Reward Entries.
	/// </summary>
	public partial class DestinyMilestoneRewardEntry
	{
		[JsonProperty("rewardEntryHash")]
		public uint RewardEntryHash { get; set; }

		[JsonProperty("earned")]
		public bool Earned { get; set; }

		[JsonProperty("redeemed")]
		public bool Redeemed { get; set; }
	}
}
