// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Challenges
{
	/// <summary>
	/// Represents the status and other related information for a challenge that is - or was - available to a player. 
	/// A challenge is a bonus objective, generally tacked onto Quests or Activities, that provide additional variations on play.
	/// </summary>
	public partial class DestinyChallengeStatus
	{
		[JsonProperty("objective")]
		public Destiny.Quests.DestinyObjectiveProgress Objective { get; set; }
	}
}
