//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Config
{
	public partial class GearAssetDataBaseDefinition
	{
		[JsonProperty("version")]
		public int Version { get; set; }

		[JsonProperty("path")]
		public string Path { get; set; }
	}
}
