//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Forums
{
	[Flags]
	public enum ForumPostCategoryEnums
	{
		None = 0x0,

		TextOnly = 0x1,

		Media = 0x2,

		Link = 0x4,

		Poll = 0x8,

		Question = 0x10,

		Answered = 0x20,

		Announcement = 0x40,

		ContentComment = 0x80,

		BungieOfficial = 0x100,

		NinjaOfficial = 0x200,

		Recruitment = 0x400
	}
}
