// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Collectibles
{
	public partial class DestinyCollectibleComponent
	{
		[JsonProperty("state")]
		public Destiny.DestinyCollectibleState State { get; set; }
	}
}
