//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	[Flags]
	public enum Capabilities
	{
		None = 0x0,

		Leaderboards = 0x1,

		Callsign = 0x2,

		OptionalConversations = 0x4,

		ClanBanner = 0x8,

		D2InvestmentData = 0x10,

		Tags = 0x20,

		Alliances = 0x40
	}
}
