// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum ChatSecuritySetting
	{
		Group = 0,

		Admins = 1
	}
}
