// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.GroupsV2
{
	public partial class GroupEditAction
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("about")]
		public string About { get; set; }

		[JsonProperty("motto")]
		public string Motto { get; set; }

		[JsonProperty("theme")]
		public string Theme { get; set; }

		[JsonProperty("avatarImageIndex")]
		public int? AvatarImageIndex { get; set; }

		[JsonProperty("tags")]
		public string Tags { get; set; }

		[JsonProperty("isPublic")]
		public bool? IsPublic { get; set; }

		[JsonProperty("membershipOption")]
		public GroupsV2.MembershipOption? MembershipOption { get; set; }

		[JsonProperty("isPublicTopicAdminOnly")]
		public bool? IsPublicTopicAdminOnly { get; set; }

		[JsonProperty("allowChat")]
		public bool? AllowChat { get; set; }

		[JsonProperty("chatSecurity")]
		public GroupsV2.ChatSecuritySetting? ChatSecurity { get; set; }

		[JsonProperty("callsign")]
		public string Callsign { get; set; }

		[JsonProperty("locale")]
		public string Locale { get; set; }

		[JsonProperty("homepage")]
		public GroupsV2.GroupHomepage? Homepage { get; set; }

		[JsonProperty("enableInvitationMessagingForAdmins")]
		public bool? EnableInvitationMessagingForAdmins { get; set; }

		[JsonProperty("defaultPublicity")]
		public GroupsV2.GroupPostPublicity? DefaultPublicity { get; set; }
	}
}
