// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupHomepage
	{
		Wall = 0,

		Forum = 1,

		AllianceForum = 2
	}
}
