// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupApplicationResolveState
	{
		Unresolved = 0,

		Accepted = 1,

		Denied = 2,

		Rescinded = 3
	}
}
