// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupAllianceStatus
	{
		Unallied = 0,

		Parent = 1,

		Child = 2
	}
}
