//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.GroupsV2
{
	public partial class GroupBan
	{
		[JsonProperty("groupId")]
		public long GroupId { get; set; }

		[JsonProperty("lastModifiedBy")]
		public User.UserInfoCard LastModifiedBy { get; set; }

		[JsonProperty("createdBy")]
		public User.UserInfoCard CreatedBy { get; set; }

		[JsonProperty("dateBanned")]
		public DateTime DateBanned { get; set; }

		[JsonProperty("dateExpires")]
		public DateTime DateExpires { get; set; }

		[JsonProperty("comment")]
		public string Comment { get; set; }

		[JsonProperty("bungieNetUserInfo")]
		public User.UserInfoCard BungieNetUserInfo { get; set; }

		[JsonProperty("destinyUserInfo")]
		public GroupsV2.GroupUserInfoCard DestinyUserInfo { get; set; }
	}
}
