//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.GroupsV2
{
	public partial class GroupFeatures
	{
		[JsonProperty("maximumMembers")]
		public int MaximumMembers { get; set; }

		[JsonProperty("maximumMembershipsOfGroupType")]
		public int MaximumMembershipsOfGroupType { get; set; }

		[JsonProperty("capabilities")]
		public GroupsV2.Capabilities Capabilities { get; set; }

		[JsonProperty("membershipTypes")]
		public BungieMembershipType[] MembershipTypes { get; set; }

		[JsonProperty("invitePermissionOverride")]
		public bool InvitePermissionOverride { get; set; }

		[JsonProperty("updateCulturePermissionOverride")]
		public bool UpdateCulturePermissionOverride { get; set; }

		[JsonProperty("hostGuidedGamePermissionOverride")]
		public GroupsV2.HostGuidedGamesPermissionLevel HostGuidedGamePermissionOverride { get; set; }

		[JsonProperty("updateBannerPermissionOverride")]
		public bool UpdateBannerPermissionOverride { get; set; }

		[JsonProperty("joinLevel")]
		public GroupsV2.RuntimeGroupMemberType JoinLevel { get; set; }
	}
}
