//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.GroupsV2
{
	/// <summary>
	/// This contract contains clan-specific group information. It does not include any investment data.
	/// </summary>
	public partial class GroupV2ClanInfo
	{
		[JsonProperty("clanCallsign")]
		public string ClanCallsign { get; set; }

		[JsonProperty("clanBannerData")]
		public GroupsV2.ClanBanner ClanBannerData { get; set; }
	}
}
