// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupDateRange
	{
		All = 0,

		PastDay = 1,

		PastWeek = 2,

		PastMonth = 3,

		PastYear = 4
	}
}
