// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupSortBy
	{
		Name = 0,

		Date = 1,

		Popularity = 2,

		Id = 3
	}
}
