//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupPotentialMemberStatus
	{
		None = 0,

		Applicant = 1,

		Invitee = 2
	}
}
