//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	public enum GroupAllianceStatus
	{
		Unallied = 0,

		Parent = 1,

		Child = 2
	}
}
