//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.GroupsV2
{
	/// <summary>
	/// Used for setting the guided game permission level override (admins and founders can always host guided games).
	/// </summary>
	public enum HostGuidedGamesPermissionLevel
	{
		None = 0,

		Beginner = 1,

		Member = 2
	}
}
