// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Records
{
	public partial class DestinyRecordComponent
	{
		[JsonProperty("state")]
		public Destiny.DestinyRecordState State { get; set; }

		[JsonProperty("objectives")]
		public Destiny.Quests.DestinyObjectiveProgress[] Objectives { get; set; }
	}
}
