// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Records
{
	public partial class DestinyRecordsComponent
	{
		[JsonProperty("records")]
		public System.Collections.Generic.Dictionary<uint, Destiny.Components.Records.DestinyRecordComponent> Records { get; set; }
	}
}
