// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum BucketCategory
	{
		Invisible = 0,

		Item = 1,

		Currency = 2,

		Equippable = 3,

		Ignored = 4
	}
}
