// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	[Flags]
	/// <summary>
	/// A flags enumeration indicating the versions of the game that a given user has purchased.
	/// </summary>
	public enum DestinyGameVersions
	{
		None = 0x0,

		Destiny2 = 0x1,

		DLC1 = 0x2,

		DLC2 = 0x4
	}
}
