//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// This determines the type of reply that a Vendor will have during an Interaction.
	/// </summary>
	public enum DestinyVendorReplyType
	{
		Accept = 0,

		Decline = 1,

		Complete = 2
	}
}
