//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// An enumeration representing the potential difficulty levels of an activity. Their names are... more qualitative than quantitative.
	/// </summary>
	public enum DestinyActivityDifficultyTier
	{
		Trivial = 0,

		Easy = 1,

		Normal = 2,

		Challenging = 3,

		Hard = 4,

		Brave = 5,

		AlmostImpossible = 6,

		Impossible = 7
	}
}
