// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyAmmunitionType
	{
		None = 0,

		Primary = 1,

		Special = 2,

		Heavy = 3,

		Unknown = 4
	}
}
