//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// A player can choose to restrict requests to join their Fireteam to specific states. These are the possible states a user can choose.
	/// </summary>
	public enum DestinyGamePrivacySetting
	{
		Open = 0,

		ClanAndFriendsOnly = 1,

		FriendsOnly = 2,

		InvitationOnly = 3,

		Closed = 4
	}
}
