//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Indicates the type of filter to apply to Vendor results.
	/// </summary>
	public enum DestinyVendorFilter
	{
		None = 0
	}
}
