// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Activity Modes are grouped into a few possible broad categories.
	/// </summary>
	public enum DestinyActivityModeCategory
	{
		/// <summary>
		/// Activities that are neither PVP nor PVE, such as social activities.
		/// </summary>
		None = 0,

		/// <summary>
		/// PvE activities, where you shoot aliens in the face.
		/// </summary>
		PvE = 1,

		/// <summary>
		/// PvP activities, where you teabag other humans in the face.
		/// </summary>
		PvP = 2,

		/// <summary>
		/// PVE competitive activities.
		/// </summary>
		PvECompetitive = 3
	}
}
