//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinySocketVisibility
	{
		Visible = 0,

		Hidden = 1,

		HiddenWhenEmpty = 2,

		HiddenIfNoPlugsAvailable = 3
	}
}
