//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny
{
	/// <summary>
	/// This property has some history. A talent grid can provide stats on both the item it's related to and the character equipping the item. This returns data about those stat bonuses.
	/// </summary>
	public partial class DestinyTalentNodeStatBlock
	{
		[JsonProperty("currentStepStats")]
		public Destiny.DestinyStat[] CurrentStepStats { get; set; }

		[JsonProperty("nextStepStats")]
		public Destiny.DestinyStat[] NextStepStats { get; set; }
	}
}
