// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Represents a stat on an item *or* Character (NOT a Historical Stat, but a physical attribute stat like Attack, Defense etc...)
	/// </summary>
	public partial class DestinyStat
	{
		[JsonProperty("statHash")]
		public uint StatHash { get; set; }

		[JsonProperty("value")]
		public int Value { get; set; }

		[JsonProperty("maximumValue")]
		public int MaximumValue { get; set; }
	}
}
