//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// A Flags Enumeration where each bit represents a different state that the Collectible can be in. A collectible can be in any number of these states, and you can choose to use or ignore any or all of them when making your own UI that shows Collectible info. Our displays are going to honor them, but we're also the kind of people who only pretend to inhale before quickly passing it to the left. So, you know, do what you got to do.
	/// </summary>
	public enum DestinyCollectibleState
	{
		None = 0,

		/// <summary>
		/// If this flag is set, you have not yet obtained this collectible.
		/// </summary>
		NotAcquired = 1,

		/// <summary>
		/// If this flag is set, the item is "obscured" to you: you can/should use the alternate item hash found in DestinyCollectibleDefinition.stateInfo.obscuredOverrideItemHash when displaying this collectible instead of the default display info.
		/// </summary>
		Obscured = 2,

		/// <summary>
		/// If this flag is set, the collectible should not be shown to the user.
		/// But, I mean do what you want: I'm not your mom. It's much more likely that I'm your Dad - wait, I promised your mom that I wouldn't tell you. Don't tell her that I told you.
		/// </summary>
		Invisible = 4,

		/// <summary>
		/// If this flag is set, the collectible requires payment for creating an instance of the item, and you are lacking in currency. Bring the benjamins next time. Or spinmetal. Whatever.
		/// </summary>
		CannotAffordMaterialRequirements = 8,

		/// <summary>
		/// If this flag is set, you can't pull this item out of your collection because there's no room left in your inventory.
		/// </summary>
		InventorySpaceUnavailable = 16,

		/// <summary>
		/// If this flag is set, you already have one of these items and can't have a second one.
		/// </summary>
		UniquenessViolation = 32,

		/// <summary>
		/// If this flag is set, the ability to pull this item out of your collection has been disabled.
		/// </summary>
		PurchaseDisabled = 64
	}
}
