//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be.
	/// </summary>
	public enum DestinyVendorInteractionRewardSelection
	{
		None = 0,

		One = 1,

		All = 2
	}
}
