// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyPresentationNodeType
	{
		Default = 0,

		Category = 1,

		Collectibles = 2,

		Records = 3
	}
}
