//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyRecordToastStyle
	{
		None = 0,

		Record = 1,

		Lore = 2,

		Badge = 3,

		MetaRecord = 4,

		MedalComplete = 5
	}
}
