//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.
	/// </summary>
	public enum DestinyProgressionStepDisplayEffect
	{
		None = 0,

		Character = 1,

		Item = 2
	}
}
