//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyAmmunitionType
	{
		None = 0,

		Primary = 1,

		Special = 2,

		Heavy = 3,

		Unknown = 4
	}
}
