//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Represents the possible and known UI styles used by the game for rendering Socket Categories.
	/// </summary>
	public enum DestinySocketCategoryStyle
	{
		Unknown = 0,

		Reusable = 1,

		Consumable = 2,

		Unlockable = 3,

		Intrinsic = 4
	}
}
