//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyPresentationNodeType
	{
		Default = 0,

		Category = 1,

		Collectibles = 2,

		Records = 3,

		Metric = 4
	}
}
