//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Activity Modes are grouped into a few possible broad categories.
	/// </summary>
	public enum DestinyActivityModeCategory
	{
		/// <summary>
		/// Activities that are neither PVP nor PVE, such as social activities.
		/// </summary>
		None = 0,

		/// <summary>
		/// PvE activities, where you shoot aliens in the face.
		/// </summary>
		PvE = 1,

		/// <summary>
		/// PvP activities, where you shoot your "friends".
		/// </summary>
		PvP = 2,

		/// <summary>
		/// PVE competitive activities, where you shoot whoever you want whenever you want. Or run around collecting small glowing triangles.
		/// </summary>
		PvECompetitive = 3
	}
}
