//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// The action that happens when the user attempts to refund an item.
	/// </summary>
	public enum DestinyVendorItemRefundPolicy
	{
		NotRefundable = 0,

		DeletesItem = 1,

		RevokesLicense = 2
	}
}
