// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyRecordValueStyle
	{
		Integer = 0,

		Percentage = 1,

		Milliseconds = 2,

		Boolean = 3,

		Decimal = 4
	}
}
