// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum DestinyGender
	{
		Male = 0,

		Female = 1,

		Unknown = 2
	}
}
