//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Determines how items are sorted in an inventory bucket.
	/// </summary>
	public enum DestinyItemSortType
	{
		ItemId = 0,

		Timestamp = 1,

		StackSize = 2
	}
}
