// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Represents a potential state of an Activity Graph node.
	/// </summary>
	public enum DestinyGraphNodeState
	{
		Hidden = 0,

		Visible = 1,

		Teaser = 2,

		Incomplete = 3,

		Completed = 4
	}
}
