// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum ItemLocation
	{
		Unknown = 0,

		Inventory = 1,

		Vault = 2,

		Vendor = 3,

		Postmaster = 4
	}
}
