//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum ItemLocation
	{
		Unknown = 0,

		Inventory = 1,

		Vault = 2,

		Vendor = 3,

		Postmaster = 4
	}
}
