// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Indicates the type of actions that can be performed
	/// </summary>
	public enum SocketTypeActionType
	{
		InsertPlug = 0,

		InfuseItem = 1,

		ReinitializeSocket = 2
	}
}
