// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	public enum TierType
	{
		Unknown = 0,

		Currency = 1,

		Basic = 2,

		Common = 3,

		Rare = 4,

		Superior = 5,

		Exotic = 6
	}
}
