//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Whether you can transfer an item, and why not if you can't.
	/// </summary>
	[Flags]
	public enum TransferStatuses
	{
		/// <summary>
		/// The item can be transferred.
		/// </summary>
		CanTransfer = 0x0,

		/// <summary>
		/// You can't transfer the item because it is equipped on a character.
		/// </summary>
		ItemIsEquipped = 0x1,

		/// <summary>
		/// The item is defined as not transferrable in its DestinyInventoryItemDefinition.nonTransferrable property.
		/// </summary>
		NotTransferrable = 0x2,

		/// <summary>
		/// You could transfer the item, but the place you're trying to put it has run out of room! Check your remaining Vault and/or character space.
		/// </summary>
		NoRoomInDestination = 0x4
	}
}
