//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// Display categories can have custom sort orders. These are the possible options.
	/// </summary>
	public enum VendorDisplayCategorySortOrder
	{
		Default = 0,

		SortByTier = 1
	}
}
