// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Config
{
	public partial class GroupTheme
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("folder")]
		public string Folder { get; set; }

		[JsonProperty("description")]
		public string Description { get; set; }
	}
}
