//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Config
{
	public partial class GroupTheme
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("folder")]
		public string Folder { get; set; }

		[JsonProperty("description")]
		public string Description { get; set; }
	}
}
