//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Config
{
	public partial class UserTheme
	{
		[JsonProperty("userThemeId")]
		public int UserThemeId { get; set; }

		[JsonProperty("userThemeName")]
		public string UserThemeName { get; set; }

		[JsonProperty("userThemeDescription")]
		public string UserThemeDescription { get; set; }
	}
}
