//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Checklists
{
	/// <summary>
	/// The properties of an individual checklist item. Note that almost everything is optional: it is *highly* variable what kind of data we'll actually be able to return: at times we may have no other relationships to entities at all.
	/// Whatever UI you build, do it with the knowledge that any given entry might not actually be able to be associated with some other Destiny entity.
	/// </summary>
	public partial class DestinyChecklistEntryDefinition
	{
		[JsonProperty("hash")]
		public uint Hash { get; set; }

		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("destinationHash")]
		public uint? DestinationHash { get; set; }

		[JsonProperty("locationHash")]
		public uint? LocationHash { get; set; }

		[JsonProperty("bubbleHash")]
		public uint? BubbleHash { get; set; }

		[JsonProperty("activityHash")]
		public uint? ActivityHash { get; set; }

		[JsonProperty("itemHash")]
		public uint? ItemHash { get; set; }

		[JsonProperty("vendorHash")]
		public uint? VendorHash { get; set; }

		[JsonProperty("vendorInteractionIndex")]
		public int? VendorInteractionIndex { get; set; }

		[JsonProperty("scope")]
		public Destiny.DestinyScope Scope { get; set; }
	}
}
