// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Common.Models
{
	public partial class CoreSystem
	{
		[JsonProperty("enabled")]
		public bool Enabled { get; set; }

		[JsonProperty("parameters")]
		public System.Collections.Generic.Dictionary<string, string> Parameters { get; set; }
	}
}
