//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Common.Models
{
	public partial class CoreSettingsConfiguration
	{
		[JsonProperty("environment")]
		public string Environment { get; set; }

		[JsonProperty("systems")]
		public System.Collections.Generic.Dictionary<string, Common.Models.CoreSystem> Systems { get; set; }

		[JsonProperty("ignoreReasons")]
		public Common.Models.CoreSetting[] IgnoreReasons { get; set; }

		[JsonProperty("forumCategories")]
		public Common.Models.CoreSetting[] ForumCategories { get; set; }

		[JsonProperty("groupAvatars")]
		public Common.Models.CoreSetting[] GroupAvatars { get; set; }

		[JsonProperty("destinyMembershipTypes")]
		public Common.Models.CoreSetting[] DestinyMembershipTypes { get; set; }

		[JsonProperty("recruitmentPlatformTags")]
		public Common.Models.CoreSetting[] RecruitmentPlatformTags { get; set; }

		[JsonProperty("recruitmentMiscTags")]
		public Common.Models.CoreSetting[] RecruitmentMiscTags { get; set; }

		[JsonProperty("recruitmentActivities")]
		public Common.Models.CoreSetting[] RecruitmentActivities { get; set; }

		[JsonProperty("userContentLocales")]
		public Common.Models.CoreSetting[] UserContentLocales { get; set; }

		[JsonProperty("systemContentLocales")]
		public Common.Models.CoreSetting[] SystemContentLocales { get; set; }

		[JsonProperty("clanBannerDecals")]
		public Common.Models.CoreSetting[] ClanBannerDecals { get; set; }

		[JsonProperty("clanBannerDecalColors")]
		public Common.Models.CoreSetting[] ClanBannerDecalColors { get; set; }

		[JsonProperty("clanBannerGonfalons")]
		public Common.Models.CoreSetting[] ClanBannerGonfalons { get; set; }

		[JsonProperty("clanBannerGonfalonColors")]
		public Common.Models.CoreSetting[] ClanBannerGonfalonColors { get; set; }

		[JsonProperty("clanBannerGonfalonDetails")]
		public Common.Models.CoreSetting[] ClanBannerGonfalonDetails { get; set; }

		[JsonProperty("clanBannerGonfalonDetailColors")]
		public Common.Models.CoreSetting[] ClanBannerGonfalonDetailColors { get; set; }

		[JsonProperty("clanBannerStandards")]
		public Common.Models.CoreSetting[] ClanBannerStandards { get; set; }

		[JsonProperty("destiny2CoreSettings")]
		public Common.Models.Destiny2CoreSettings Destiny2CoreSettings { get; set; }

		[JsonProperty("emailSettings")]
		public User.EmailSettings EmailSettings { get; set; }

		[JsonProperty("fireteamActivities")]
		public Common.Models.CoreSetting[] FireteamActivities { get; set; }
	}
}
