//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.PowerCaps
{
	/// <summary>
	/// Defines a 'power cap' (limit) for gear items, based on the rarity tier and season of release.
	/// </summary>
	public partial class DestinyPowerCapDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("powerCap")]
		public int PowerCap { get; set; }
	}
}
