//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Streaming
{
	public enum DropStateEnum : byte
	{
		Claimed = 0,

		Applied = 1,

		Fulfilled = 2
	}
}
