// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Requests
{
	public partial class DestinyItemTransferRequest
	{
		[JsonProperty("itemReferenceHash")]
		public uint ItemReferenceHash { get; set; }

		[JsonProperty("stackSize")]
		public int StackSize { get; set; }

		[JsonProperty("transferToVault")]
		public bool TransferToVault { get; set; }

		[JsonProperty("itemId")]
		public long ItemId { get; set; }

		[JsonProperty("characterId")]
		public long CharacterId { get; set; }

		[JsonProperty("membershipType")]
		public BungieMembershipType MembershipType { get; set; }
	}
}
