//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Social.Friends
{
	public partial class BungieFriendListResponse
	{
		[JsonProperty("friends")]
		public Social.Friends.BungieFriend[] Friends { get; set; }
	}
}
