//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Social.Friends
{
	public enum FriendRelationshipState
	{
		Unknown = 0,

		Friend = 1,

		IncomingRequest = 2,

		OutgoingRequest = 3
	}
}
