//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Queries
{
	public partial class PagedQuery
	{
		[JsonProperty("itemsPerPage")]
		public int ItemsPerPage { get; set; }

		[JsonProperty("currentPage")]
		public int CurrentPage { get; set; }

		[JsonProperty("requestContinuationToken")]
		public string RequestContinuationToken { get; set; }
	}
}
