//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.StringVariables
{
	public partial class DestinyStringVariablesComponent
	{
		[JsonProperty("integerValuesByHash")]
		public System.Collections.Generic.Dictionary<uint, int> IntegerValuesByHash { get; set; }
	}
}
