using System;
using System.IO;

namespace LibraryGenerator
{
	public class FileBuilder
	{
		public string[] FolderPaths { get; set; }
		public string FileName { get; set; }

		public Builder Builder { get; set; }

		public virtual void Write(TextWriter writer)
		{
			WriteAutoGeneratedFileHeader(writer);

			Builder.Write(writer);
		}

		private static void WriteAutoGeneratedFileHeader(TextWriter writer)
		{
			writer.WriteLine("// " + new string('-', 77));
			writer.WriteLine("// <auto-generated>");
			writer.WriteLine("// This code was generated by a tool.  Any changes may be lost.");
			writer.WriteLine("// </auto-generated>");
			writer.WriteLine("// " + new string('-', 77));
			writer.WriteLine();
		}
	}
}
