//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	public partial class DestinyMilestoneChallengeDefinition
	{
		[JsonProperty("challengeObjectiveHash")]
		public uint ChallengeObjectiveHash { get; set; }
	}
}
