//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	/// <summary>
	/// Any data we need to figure out whether this Quest Item is the currently active one for the conceptual Milestone. Even just typing this description, I already regret it.
	/// </summary>
	public partial class DestinyMilestoneQuestDefinition
	{
		[JsonProperty("questItemHash")]
		public uint QuestItemHash { get; set; }

		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("overrideImage")]
		public string OverrideImage { get; set; }

		[JsonProperty("questRewards")]
		public Destiny.Definitions.Milestones.DestinyMilestoneQuestRewardsDefinition QuestRewards { get; set; }

		[JsonProperty("activities")]
		public System.Collections.Generic.Dictionary<uint, Destiny.Definitions.Milestones.DestinyMilestoneActivityDefinition> Activities { get; set; }

		[JsonProperty("destinationHash")]
		public uint? DestinationHash { get; set; }
	}
}
