// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	/// <summary>
	/// Represents a variant on an activity for a Milestone: a specific difficulty tier, or a specific activity variant for example.
	/// These will often have more specific details, such as an associated Guided Game, progression steps, tier-specific rewards, and custom values.
	/// </summary>
	public partial class DestinyMilestoneActivityVariantDefinition
	{
		[JsonProperty("activityHash")]
		public uint ActivityHash { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }
	}
}
