// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	public partial class DestinyMilestoneChallengeDefinition
	{
		[JsonProperty("challengeObjectiveHash")]
		public uint ChallengeObjectiveHash { get; set; }
	}
}
