//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	/// <summary>
	/// The definition of a category of rewards, that contains many individual rewards.
	/// </summary>
	public partial class DestinyMilestoneRewardCategoryDefinition
	{
		[JsonProperty("categoryHash")]
		public uint CategoryHash { get; set; }

		[JsonProperty("categoryIdentifier")]
		public string CategoryIdentifier { get; set; }

		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("rewardEntries")]
		public System.Collections.Generic.Dictionary<uint, Destiny.Definitions.Milestones.DestinyMilestoneRewardEntryDefinition> RewardEntries { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }
	}
}
