//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Milestones
{
	public partial class DestinyMilestoneChallengeActivityDefinition
	{
		[JsonProperty("activityHash")]
		public uint ActivityHash { get; set; }

		[JsonProperty("challenges")]
		public Destiny.Definitions.Milestones.DestinyMilestoneChallengeDefinition[] Challenges { get; set; }

		[JsonProperty("activityGraphNodes")]
		public Destiny.Definitions.Milestones.DestinyMilestoneChallengeActivityGraphNodeEntry[] ActivityGraphNodes { get; set; }

		[JsonProperty("phases")]
		public Destiny.Definitions.Milestones.DestinyMilestoneChallengeActivityPhase[] Phases { get; set; }
	}
}
