//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Entities.Profiles
{
	/// <summary>
	/// For now, this isn't used for much: it's a record of the recent refundable purchases that the user has made. In the future, it could be used for providing refunds/buyback via the API. Wouldn't that be fun?
	/// </summary>
	public partial class DestinyVendorReceiptsComponent
	{
		[JsonProperty("receipts")]
		public Destiny.Vendors.DestinyVendorReceipt[] Receipts { get; set; }
	}
}
