// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Director
{
	public partial class DestinyLinkedGraphEntryDefinition
	{
		[JsonProperty("activityGraphHash")]
		public uint ActivityGraphHash { get; set; }
	}
}
