// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	public partial class DestinyHistoricalWeaponStats
	{
		[JsonProperty("referenceId")]
		public uint ReferenceId { get; set; }

		[JsonProperty("values")]
		public System.Collections.Generic.Dictionary<string, Destiny.HistoricalStats.DestinyHistoricalStatsValue> Values { get; set; }
	}
}
