//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	public partial class DestinyPostGameCarnageReportTeamEntry
	{
		[JsonProperty("teamId")]
		public int TeamId { get; set; }

		[JsonProperty("standing")]
		public Destiny.HistoricalStats.DestinyHistoricalStatsValue Standing { get; set; }

		[JsonProperty("score")]
		public Destiny.HistoricalStats.DestinyHistoricalStatsValue Score { get; set; }

		[JsonProperty("teamName")]
		public string TeamName { get; set; }
	}
}
