// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	public partial class DestinyLeaderboardEntry
	{
		[JsonProperty("rank")]
		public int Rank { get; set; }

		[JsonProperty("player")]
		public Destiny.HistoricalStats.DestinyPlayer Player { get; set; }

		[JsonProperty("characterId")]
		public long CharacterId { get; set; }

		[JsonProperty("value")]
		public Destiny.HistoricalStats.DestinyHistoricalStatsValue Value { get; set; }
	}
}
