// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	public partial class DestinyPostGameCarnageReportExtendedData
	{
		[JsonProperty("weapons")]
		public Destiny.HistoricalStats.DestinyHistoricalWeaponStats[] Weapons { get; set; }

		[JsonProperty("values")]
		public System.Collections.Generic.Dictionary<string, Destiny.HistoricalStats.DestinyHistoricalStatsValue> Values { get; set; }
	}
}
