//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	/// <summary>
	/// Summary information about the activity that was played.
	/// </summary>
	public partial class DestinyHistoricalStatsActivity
	{
		[JsonProperty("referenceId")]
		public uint ReferenceId { get; set; }

		[JsonProperty("directorActivityHash")]
		public uint DirectorActivityHash { get; set; }

		[JsonProperty("instanceId")]
		public long InstanceId { get; set; }

		[JsonProperty("mode")]
		public Destiny.HistoricalStats.Definitions.DestinyActivityModeType Mode { get; set; }

		[JsonProperty("modes")]
		public Destiny.HistoricalStats.Definitions.DestinyActivityModeType[] Modes { get; set; }

		[JsonProperty("isPrivate")]
		public bool IsPrivate { get; set; }

		[JsonProperty("membershipType")]
		public BungieMembershipType MembershipType { get; set; }
	}
}
