// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.HistoricalStats
{
	public partial class DestinyHistoricalStatsValuePair
	{
		[JsonProperty("value")]
		public double Value { get; set; }

		[JsonProperty("displayValue")]
		public string DisplayValue { get; set; }
	}
}
