//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Profiles
{
	/// <summary>
	/// This is an experimental set of data that Bungie considers to be "transitory" - information that may be useful for API users, but that is coming from a non-authoritative data source about information that could potentially change at a more frequent pace than Bungie.net will receive updates about it.
	/// This information is provided exclusively for convenience should any of it be useful to users: we provide no guarantees to the accuracy or timeliness of data that comes from this source. Know that this data can potentially be out-of-date or even wrong entirely if the user disconnected from the game or suddenly changed their status before we can receive refreshed data.
	/// </summary>
	public partial class DestinyProfileTransitoryComponent
	{
		[JsonProperty("partyMembers")]
		public Destiny.Components.Profiles.DestinyProfileTransitoryPartyMember[] PartyMembers { get; set; }

		[JsonProperty("currentActivity")]
		public Destiny.Components.Profiles.DestinyProfileTransitoryCurrentActivity CurrentActivity { get; set; }

		[JsonProperty("joinability")]
		public Destiny.Components.Profiles.DestinyProfileTransitoryJoinability Joinability { get; set; }

		[JsonProperty("tracking")]
		public Destiny.Components.Profiles.DestinyProfileTransitoryTrackingEntry[] Tracking { get; set; }

		[JsonProperty("lastOrbitedDestinationHash")]
		public uint? LastOrbitedDestinationHash { get; set; }
	}
}
