//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Profiles
{
	/// <summary>
	/// If you are playing in an activity, this is some information about it.
	/// Note that we cannot guarantee any of this resembles what ends up in the PGCR in any way. They are sourced by two entirely separate systems with their own logic, and the one we source this data from should be considered non-authoritative in comparison.
	/// </summary>
	public partial class DestinyProfileTransitoryCurrentActivity
	{
		[JsonProperty("startTime")]
		public DateTime? StartTime { get; set; }

		[JsonProperty("endTime")]
		public DateTime? EndTime { get; set; }

		[JsonProperty("score")]
		public decimal Score { get; set; }

		[JsonProperty("highestOpposingFactionScore")]
		public decimal HighestOpposingFactionScore { get; set; }

		[JsonProperty("numberOfOpponents")]
		public int NumberOfOpponents { get; set; }

		[JsonProperty("numberOfPlayers")]
		public int NumberOfPlayers { get; set; }
	}
}
