//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Profiles
{
	/// <summary>
	/// The set of progression-related information that applies at a Profile-wide level for your Destiny experience. This differs from the Jimi Hendrix Experience because there's less guitars on fire. Yet. #spoileralert?
	/// This will include information such as Checklist info.
	/// </summary>
	public partial class DestinyProfileProgressionComponent
	{
		[JsonProperty("checklists")]
		public System.Collections.Generic.Dictionary<uint, System.Collections.Generic.Dictionary<uint, bool>> Checklists { get; set; }
	}
}
