//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Craftables
{
	public partial class DestinyCraftableComponent
	{
		[JsonProperty("visible")]
		public bool Visible { get; set; }

		[JsonProperty("failedRequirementIndexes")]
		public int[] FailedRequirementIndexes { get; set; }

		[JsonProperty("sockets")]
		public Destiny.Components.Craftables.DestinyCraftableSocketComponent[] Sockets { get; set; }
	}
}
