//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace BungieNet.Api
{
	public interface ICommunityContentClient
	{
		Forum.PostSearchResponse GetCommunityContent(Forum.CommunityContentSortMode sort, Forum.ForumTopicsCategoryFiltersEnum mediaFilter, int page);
		Task<Forum.PostSearchResponse> GetCommunityContentAsync(Forum.CommunityContentSortMode sort, Forum.ForumTopicsCategoryFiltersEnum mediaFilter, int page);
	}

	partial interface IBungieClient
	{
		ICommunityContentClient CommunityContent { get; }
	}

	partial class BungieClient : ICommunityContentClient
	{
		public ICommunityContentClient CommunityContent => this;


		Forum.PostSearchResponse ICommunityContentClient.GetCommunityContent(Forum.CommunityContentSortMode sort, Forum.ForumTopicsCategoryFiltersEnum mediaFilter, int page) => CommunityContent.GetCommunityContentAsync(sort, mediaFilter, page).GetAwaiter().GetResult();
		Task<Forum.PostSearchResponse> ICommunityContentClient.GetCommunityContentAsync(Forum.CommunityContentSortMode sort, Forum.ForumTopicsCategoryFiltersEnum mediaFilter, int page)
		{
			string[] pathSegments = new string[] { "CommunityContent", "Get", ((byte)sort).ToString(), ((int)mediaFilter).ToString(), page.ToString() };
			Uri uri = GetEndpointUri(BungieEndpointBase.Default, pathSegments, true, null);
			return GetEntityAsync<Forum.PostSearchResponse>(uri);
		}
	}
}
