//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.User
{
	/// <summary>
	/// The set of all email subscription/opt-in settings and definitions.
	/// </summary>
	public partial class EmailSettings
	{
		[JsonProperty("optInDefinitions")]
		public System.Collections.Generic.Dictionary<string, User.EmailOptInDefinition> OptInDefinitions { get; set; }

		[JsonProperty("subscriptionDefinitions")]
		public System.Collections.Generic.Dictionary<string, User.EmailSubscriptionDefinition> SubscriptionDefinitions { get; set; }

		[JsonProperty("views")]
		public System.Collections.Generic.Dictionary<string, User.EmailViewDefinition> Views { get; set; }
	}
}
