//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.User
{
	[Flags]
	public enum OptInFlags : long
	{
		Newsletter = 0x1,

		System = 0x2,

		Marketing = 0x4,

		UserResearch = 0x8,

		CustomerService = 0x10,

		Social = 0x20
	}
}
