//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.User
{
	public partial class UserSearchResponseDetail
	{
		[JsonProperty("bungieGlobalDisplayName")]
		public string BungieGlobalDisplayName { get; set; }

		[JsonProperty("bungieGlobalDisplayNameCode")]
		public short? BungieGlobalDisplayNameCode { get; set; }

		[JsonProperty("bungieNetMembershipId")]
		public long? BungieNetMembershipId { get; set; }

		[JsonProperty("destinyMemberships")]
		public User.UserInfoCard[] DestinyMemberships { get; set; }
	}
}
