//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Seasons
{
	/// <summary>
	/// Defines the properties of an 'Event Card' in Destiny 2, to coincide with a seasonal event for additional challenges, premium rewards, a new seal, and a special title. For example: Solstice of Heroes 2022.
	/// </summary>
	public partial class DestinyEventCardDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("linkRedirectPath")]
		public string LinkRedirectPath { get; set; }

		[JsonProperty("color")]
		public Destiny.Misc.DestinyColor Color { get; set; }

		[JsonProperty("images")]
		public Destiny.Definitions.Seasons.DestinyEventCardImages Images { get; set; }

		[JsonProperty("triumphsPresentationNodeHash")]
		public uint TriumphsPresentationNodeHash { get; set; }

		[JsonProperty("sealPresentationNodeHash")]
		public uint SealPresentationNodeHash { get; set; }

		[JsonProperty("ticketCurrencyItemHash")]
		public uint TicketCurrencyItemHash { get; set; }

		[JsonProperty("ticketVendorHash")]
		public uint TicketVendorHash { get; set; }

		[JsonProperty("ticketVendorCategoryHash")]
		public uint TicketVendorCategoryHash { get; set; }

		[JsonProperty("endTime")]
		public long EndTime { get; set; }
	}
}
