// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	public enum CommunityContentSortMode : byte
	{
		Trending = 0,

		Latest = 1,

		HighestRated = 2
	}
}
