// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	public enum ForumPostSortEnum
	{
		Default = 0,

		OldestFirst = 1
	}
}
