// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	public enum ForumRecruitmentToneLabel : byte
	{
		None = 0,

		FamilyFriendly = 1,

		Rowdy = 2
	}
}
