//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	[Flags]
	public enum ForumTopicsCategoryFiltersEnum
	{
		None = 0x0,

		Links = 0x1,

		Questions = 0x2,

		AnsweredQuestions = 0x4,

		Media = 0x8,

		TextOnly = 0x10,

		Announcement = 0x20,

		BungieOfficial = 0x40,

		Polls = 0x80
	}
}
