//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	public enum ForumPostPopularity
	{
		Empty = 0,

		Default = 1,

		Discussed = 2,

		CoolStory = 3,

		HeatingUp = 4,

		Hot = 5
	}
}
