// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	public enum ForumTopicsSortEnum : byte
	{
		Default = 0,

		LastReplied = 1,

		MostReplied = 2,

		Popularity = 3,

		Controversiality = 4,

		Liked = 5,

		HighestRated = 6,

		MostUpvoted = 7
	}
}
