// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Forum
{
	[Flags]
	public enum ForumFlagsEnum
	{
		None = 0x0,

		BungieStaffPost = 0x1,

		ForumNinjaPost = 0x2,

		ForumMentorPost = 0x4,

		TopicBungieStaffPosted = 0x8,

		TopicBungieVolunteerPosted = 0x10,

		QuestionAnsweredByBungie = 0x20,

		QuestionAnsweredByNinja = 0x40,

		CommunityContent = 0x80
	}
}
