// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Forum
{
	public partial class PollResponse
	{
		[JsonProperty("topicId")]
		public long TopicId { get; set; }

		[JsonProperty("results")]
		public Forum.PollResult[] Results { get; set; }

		[JsonProperty("totalVotes")]
		public int TotalVotes { get; set; }
	}
}
