//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Applications
{
	public partial class ApplicationDeveloper
	{
		[JsonProperty("role")]
		public Applications.DeveloperRole Role { get; set; }

		[JsonProperty("apiEulaVersion")]
		public int ApiEulaVersion { get; set; }

		[JsonProperty("user")]
		public User.UserInfoCard User { get; set; }
	}
}
