//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Applications
{
	public partial class Datapoint
	{
		[JsonProperty("time")]
		public DateTime Time { get; set; }

		[JsonProperty("count")]
		public decimal? Count { get; set; }
	}
}
