// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Applications
{
	public partial class Datapoint
	{
		[JsonProperty("time")]
		public DateTime Time { get; set; }

		[JsonProperty("count")]
		public double? Count { get; set; }
	}
}
