//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Applications
{
	public enum DeveloperRole
	{
		None = 0,

		Owner = 1,

		TeamMember = 2
	}
}
