// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Applications
{
	public enum DeveloperRole
	{
		None = 0,

		Owner = 1,

		TeamMember = 2
	}
}
