//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Records
{
	public partial class DestinyRecordIntervalObjective
	{
		[JsonProperty("intervalObjectiveHash")]
		public uint IntervalObjectiveHash { get; set; }

		[JsonProperty("intervalScoreValue")]
		public int IntervalScoreValue { get; set; }
	}
}
