//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Records
{
	/// <summary>
	/// If this record has an expiration after which it cannot be earned, this is some information about that expiration.
	/// </summary>
	public partial class DestinyRecordExpirationBlock
	{
		[JsonProperty("hasExpiration")]
		public bool HasExpiration { get; set; }

		[JsonProperty("description")]
		public string Description { get; set; }

		[JsonProperty("icon")]
		public string Icon { get; set; }
	}
}
