//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Records
{
	public partial class DestinyRecordTitleBlock
	{
		[JsonProperty("hasTitle")]
		public bool HasTitle { get; set; }

		[JsonProperty("titlesByGender")]
		public System.Collections.Generic.Dictionary<Destiny.DestinyGender, string> TitlesByGender { get; set; }

		[JsonProperty("titlesByGenderHash")]
		public System.Collections.Generic.Dictionary<uint, string> TitlesByGenderHash { get; set; }
	}
}
