// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Records
{
	public partial class SchemaRecordStateBlock
	{
		[JsonProperty("featuredPriority")]
		public int FeaturedPriority { get; set; }

		[JsonProperty("obscuredString")]
		public string ObscuredString { get; set; }
	}
}
