//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Activities
{
	/// <summary>
	/// Represents the public-facing status of an activity: any data about what is currently active in the Activity, regardless of an individual character's progress in it.
	/// </summary>
	public partial class DestinyPublicActivityStatus
	{
		[JsonProperty("challengeObjectiveHashes")]
		public uint[] ChallengeObjectiveHashes { get; set; }

		[JsonProperty("modifierHashes")]
		public uint[] ModifierHashes { get; set; }

		[JsonProperty("rewardTooltipItems")]
		public Destiny.DestinyItemQuantity[] RewardTooltipItems { get; set; }
	}
}
