//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Config.ClanBanner
{
	public partial class ClanBannerDecal
	{
		[JsonProperty("identifier")]
		public string Identifier { get; set; }

		[JsonProperty("foregroundPath")]
		public string ForegroundPath { get; set; }

		[JsonProperty("backgroundPath")]
		public string BackgroundPath { get; set; }
	}
}
