//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Vendors
{
	/// <summary>
	/// This component contains essential/summary information about the vendor.
	/// </summary>
	public partial class DestinyVendorBaseComponent
	{
		[JsonProperty("vendorHash")]
		public uint VendorHash { get; set; }

		[JsonProperty("nextRefreshDate")]
		public DateTime NextRefreshDate { get; set; }

		[JsonProperty("enabled")]
		public bool Enabled { get; set; }
	}
}
