//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Components.Vendors
{
	/// <summary>
	/// Has character-agnostic information about an item being sold by a vendor.
	/// Note that if you want instance, stats, etc... data for the item, you'll have to request additional components such as ItemInstances, ItemPerks etc... and acquire them from the DestinyVendorResponse's "items" property. For most of these, however, you'll have to ask for it in context of a specific character.
	/// </summary>
	public partial class DestinyPublicVendorSaleItemComponent
	{
		[JsonProperty("vendorItemIndex")]
		public int VendorItemIndex { get; set; }

		[JsonProperty("itemHash")]
		public uint ItemHash { get; set; }

		[JsonProperty("overrideStyleItemHash")]
		public uint? OverrideStyleItemHash { get; set; }

		[JsonProperty("quantity")]
		public int Quantity { get; set; }

		[JsonProperty("costs")]
		public Destiny.DestinyItemQuantity[] Costs { get; set; }

		[JsonProperty("overrideNextRefreshDate")]
		public DateTime? OverrideNextRefreshDate { get; set; }
	}
}
