using System;
using System.IO;

namespace LibraryGenerator
{
	public class FileBuilder
	{
		public string[] FolderPaths { get; set; }
		public string FileName { get; set; }

		public Builder Builder { get; set; }

		public virtual void Write(TextWriter writer)
		{
			WriteAutoGeneratedFileHeader(writer);

			Builder.Write(writer);
		}

		private static void WriteAutoGeneratedFileHeader(TextWriter writer)
		{
			writer.WriteLine("//------------------------------------------------------------------------------");
			writer.WriteLine("// <auto-generated>");
			writer.WriteLine("//     This code was generated by a tool.");
			writer.WriteLine("//");
			writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
			writer.WriteLine("//     the code is regenerated.");
			writer.WriteLine("// </auto-generated>");
			writer.WriteLine("//------------------------------------------------------------------------------");
			writer.WriteLine();
		}
	}
}
