// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Fireteam
{
	public partial class FireteamResponse
	{
		[JsonProperty("Summary")]
		public Fireteam.FireteamSummary Summary { get; set; }

		[JsonProperty("Members")]
		public Fireteam.FireteamMember[] Members { get; set; }

		[JsonProperty("Alternates")]
		public Fireteam.FireteamMember[] Alternates { get; set; }
	}
}
