//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Fireteam
{
	public enum FireteamSlotSearch : byte
	{
		NoSlotRestriction = 0,

		HasOpenPlayerSlots = 1,

		HasOpenPlayerOrAltSlots = 2
	}
}
