//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Fireteam
{
	public enum FireteamDateRange : byte
	{
		All = 0,

		Now = 1,

		TwentyFourHours = 2,

		FortyEightHours = 3,

		ThisWeek = 4
	}
}
