//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Fireteam
{
	public partial class FireteamResponse
	{
		[JsonProperty("Summary")]
		public Fireteam.FireteamSummary Summary { get; set; }

		[JsonProperty("Members")]
		public Fireteam.FireteamMember[] Members { get; set; }

		[JsonProperty("Alternates")]
		public Fireteam.FireteamMember[] Alternates { get; set; }
	}
}
