//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Fireteam
{
	public enum FireteamActivityType
	{
		All = 0,

		Raid = 1,

		Crucible = 2,

		Trials = 3,

		Nightfall = 4,

		Anything = 5,

		Gambit = 6,

		BlindWell = 7,

		EscalationProtocol = 8,

		Forge = 9,

		Reckoning = 10,

		Menagerie = 11
	}
}
