//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Entities.Vendors
{
	/// <summary>
	/// This component contains essential/summary information about the vendor.
	/// </summary>
	public partial class DestinyVendorComponent
	{
		[JsonProperty("vendorHash")]
		public uint VendorHash { get; set; }

		[JsonProperty("nextRefreshDate")]
		public DateTime NextRefreshDate { get; set; }

		[JsonProperty("enabled")]
		public bool Enabled { get; set; }

		[JsonProperty("canPurchase")]
		public bool CanPurchase { get; set; }

		[JsonProperty("progression")]
		public Destiny.DestinyProgression Progression { get; set; }

		[JsonProperty("vendorLocationIndex")]
		public int VendorLocationIndex { get; set; }

		[JsonProperty("seasonalRank")]
		public int? SeasonalRank { get; set; }
	}
}
