//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.HistoricalStats.Definitions
{
	public enum DestinyStatsMergeMethod
	{
		/// <summary>
		/// When collapsing multiple instances of the stat together, add the values.
		/// </summary>
		Add = 0,

		/// <summary>
		/// When collapsing multiple instances of the stat together, take the lower value.
		/// </summary>
		Min = 1,

		/// <summary>
		/// When collapsing multiple instances of the stat together, take the higher value.
		/// </summary>
		Max = 2
	}
}
