// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.HistoricalStats.Definitions
{
	public enum PeriodType
	{
		None = 0,

		Daily = 1,

		AllTime = 2,

		Activity = 3
	}
}
