//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Tokens
{
	public partial class TwitchDropHistoryResponse
	{
		[JsonProperty("Title")]
		public string Title { get; set; }

		[JsonProperty("Description")]
		public string Description { get; set; }

		[JsonProperty("CreatedAt")]
		public DateTime? CreatedAt { get; set; }

		[JsonProperty("ClaimState")]
		public Streaming.DropStateEnum? ClaimState { get; set; }
	}
}
