// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Sockets
{
	public partial class DestinyItemPlug
	{
		[JsonProperty("plugItemHash")]
		public uint PlugItemHash { get; set; }

		[JsonProperty("plugObjectives")]
		public Destiny.Quests.DestinyObjectiveProgress[] PlugObjectives { get; set; }

		[JsonProperty("canInsert")]
		public bool CanInsert { get; set; }

		[JsonProperty("enabled")]
		public bool Enabled { get; set; }

		[JsonProperty("insertFailIndexes")]
		public int[] InsertFailIndexes { get; set; }

		[JsonProperty("enableFailIndexes")]
		public int[] EnableFailIndexes { get; set; }
	}
}
