// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content.Models
{
	public partial class ContentTypePropertySection
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("readableName")]
		public string ReadableName { get; set; }

		[JsonProperty("collapsed")]
		public bool Collapsed { get; set; }
	}
}
