//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content.Models
{
	public partial class ContentTypePropertySection
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("readableName")]
		public string ReadableName { get; set; }

		[JsonProperty("collapsed")]
		public bool Collapsed { get; set; }
	}
}
