// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content.Models
{
	public partial class ContentTypeDefaultValue
	{
		[JsonProperty("whenClause")]
		public string WhenClause { get; set; }

		[JsonProperty("whenValue")]
		public string WhenValue { get; set; }

		[JsonProperty("defaultValue")]
		public string DefaultValue { get; set; }
	}
}
