//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content.Models
{
	public partial class ContentTypeProperty
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("rootPropertyName")]
		public string RootPropertyName { get; set; }

		[JsonProperty("readableName")]
		public string ReadableName { get; set; }

		[JsonProperty("value")]
		public string Value { get; set; }

		[JsonProperty("propertyDescription")]
		public string PropertyDescription { get; set; }

		[JsonProperty("localizable")]
		public bool Localizable { get; set; }

		[JsonProperty("fallback")]
		public bool Fallback { get; set; }

		[JsonProperty("enabled")]
		public bool Enabled { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }

		[JsonProperty("visible")]
		public bool Visible { get; set; }

		[JsonProperty("isTitle")]
		public bool IsTitle { get; set; }

		[JsonProperty("required")]
		public bool Required { get; set; }

		[JsonProperty("maxLength")]
		public int MaxLength { get; set; }

		[JsonProperty("maxByteLength")]
		public int MaxByteLength { get; set; }

		[JsonProperty("maxFileSize")]
		public int MaxFileSize { get; set; }

		[JsonProperty("regexp")]
		public string Regexp { get; set; }

		[JsonProperty("validateAs")]
		public string ValidateAs { get; set; }

		[JsonProperty("rssAttribute")]
		public string RssAttribute { get; set; }

		[JsonProperty("visibleDependency")]
		public string VisibleDependency { get; set; }

		[JsonProperty("visibleOn")]
		public string VisibleOn { get; set; }

		[JsonProperty("datatype")]
		public Content.Models.ContentPropertyDataTypeEnum Datatype { get; set; }

		[JsonProperty("attributes")]
		public System.Collections.Generic.Dictionary<string, string> Attributes { get; set; }

		[JsonProperty("childProperties")]
		public Content.Models.ContentTypeProperty[] ChildProperties { get; set; }

		[JsonProperty("contentTypeAllowed")]
		public string ContentTypeAllowed { get; set; }

		[JsonProperty("bindToProperty")]
		public string BindToProperty { get; set; }

		[JsonProperty("boundRegex")]
		public string BoundRegex { get; set; }

		[JsonProperty("representationSelection")]
		public System.Collections.Generic.Dictionary<string, string> RepresentationSelection { get; set; }

		[JsonProperty("defaultValues")]
		public Content.Models.ContentTypeDefaultValue[] DefaultValues { get; set; }

		[JsonProperty("isExternalAllowed")]
		public bool IsExternalAllowed { get; set; }

		[JsonProperty("propertySection")]
		public string PropertySection { get; set; }

		[JsonProperty("weight")]
		public int Weight { get; set; }

		[JsonProperty("entitytype")]
		public string Entitytype { get; set; }

		[JsonProperty("isCombo")]
		public bool IsCombo { get; set; }

		[JsonProperty("suppressProperty")]
		public bool SuppressProperty { get; set; }

		[JsonProperty("legalContentTypes")]
		public string[] LegalContentTypes { get; set; }

		[JsonProperty("representationValidationString")]
		public string RepresentationValidationString { get; set; }

		[JsonProperty("minWidth")]
		public int MinWidth { get; set; }

		[JsonProperty("maxWidth")]
		public int MaxWidth { get; set; }

		[JsonProperty("minHeight")]
		public int MinHeight { get; set; }

		[JsonProperty("maxHeight")]
		public int MaxHeight { get; set; }

		[JsonProperty("isVideo")]
		public bool IsVideo { get; set; }

		[JsonProperty("isImage")]
		public bool IsImage { get; set; }
	}
}
