//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Responses
{
	/// <summary>
	/// Returns the detailed information about a Collectible Presentation Node and any Collectibles that are direct descendants.
	/// </summary>
	public partial class DestinyCollectibleNodeDetailResponse
	{
		[JsonProperty("collectibles")]
		public SingleComponentResponseOfDestinyCollectiblesComponent Collectibles { get; set; }

		[JsonProperty("collectibleItemComponents")]
		public DestinyItemComponentSetOfuint32 CollectibleItemComponents { get; set; }
	}
}
