// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Responses
{
	/// <summary>
	/// The response contract for GetDestinyCharacter, with components that can be returned for character and item-level data.
	/// </summary>
	public partial class DestinyCharacterResponse
	{
		[JsonProperty("inventory")]
		public SingleComponentResponseOfDestinyInventoryComponent Inventory { get; set; }

		[JsonProperty("character")]
		public SingleComponentResponseOfDestinyCharacterComponent Character { get; set; }

		[JsonProperty("progressions")]
		public SingleComponentResponseOfDestinyCharacterProgressionComponent Progressions { get; set; }

		[JsonProperty("renderData")]
		public SingleComponentResponseOfDestinyCharacterRenderComponent RenderData { get; set; }

		[JsonProperty("activities")]
		public SingleComponentResponseOfDestinyCharacterActivitiesComponent Activities { get; set; }

		[JsonProperty("equipment")]
		public SingleComponentResponseOfDestinyInventoryComponent Equipment { get; set; }

		[JsonProperty("kiosks")]
		public SingleComponentResponseOfDestinyKiosksComponent Kiosks { get; set; }

		[JsonProperty("plugSets")]
		public SingleComponentResponseOfDestinyPlugSetsComponent PlugSets { get; set; }

		[JsonProperty("itemComponents")]
		public DestinyItemComponentSetOfint64 ItemComponents { get; set; }

		[JsonProperty("uninstancedItemComponents")]
		public DestinyBaseItemComponentSetOfuint32 UninstancedItemComponents { get; set; }

		[JsonProperty("currencyLookups")]
		public SingleComponentResponseOfDestinyCurrenciesComponent CurrencyLookups { get; set; }
	}
}
