//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Responses
{
	/// <summary>
	/// If a Destiny Profile can't be returned, but we're pretty certain it's a valid Destiny account, this will contain as much info as we can get about the profile for your use.
	/// Assume that the most you'll get is the Error Code, the Membership Type and the Membership ID.
	/// </summary>
	public partial class DestinyErrorProfile
	{
		[JsonProperty("errorCode")]
		public Exceptions.PlatformErrorCodes ErrorCode { get; set; }

		[JsonProperty("infoCard")]
		public User.UserInfoCard InfoCard { get; set; }
	}
}
