// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Responses
{
	/// <summary>
	/// A response containing all of the components for all requested vendors.
	/// </summary>
	public partial class InventoryChangedResponse
	{
		[JsonProperty("addedInventoryItems")]
		public Destiny.Entities.Items.DestinyItemComponent[] AddedInventoryItems { get; set; }

		[JsonProperty("removedInventoryItems")]
		public Destiny.Entities.Items.DestinyItemComponent[] RemovedInventoryItems { get; set; }
	}
}
