//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Sockets
{
	public partial class DestinySocketTypeScalarMaterialRequirementEntry
	{
		[JsonProperty("currencyItemHash")]
		public uint CurrencyItemHash { get; set; }

		[JsonProperty("scalarValue")]
		public int ScalarValue { get; set; }
	}
}
