//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Sockets
{
	/// <summary>
	/// Data related to what happens while a plug is being inserted, mostly for UI purposes.
	/// </summary>
	public partial class DestinyInsertPlugActionDefinition
	{
		[JsonProperty("actionExecuteSeconds")]
		public int ActionExecuteSeconds { get; set; }

		[JsonProperty("actionType")]
		public Destiny.SocketTypeActionType ActionType { get; set; }
	}
}
