// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Requests.Actions
{
	public partial class DestinyInsertPlugsActionRequest
	{
		[JsonProperty("actionToken")]
		public string ActionToken { get; set; }

		[JsonProperty("itemInstanceId")]
		public long ItemInstanceId { get; set; }

		[JsonProperty("plug")]
		public Destiny.Requests.Actions.DestinyInsertPlugsRequestEntry Plug { get; set; }

		[JsonProperty("characterId")]
		public long CharacterId { get; set; }

		[JsonProperty("membershipType")]
		public BungieMembershipType MembershipType { get; set; }
	}
}
