//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// These definitions represent faction vendors at different points in the game.
	/// A single faction may contain multiple vendors, or the same vendor available at two different locations.
	/// </summary>
	public partial class DestinyFactionVendorDefinition
	{
		[JsonProperty("vendorHash")]
		public uint VendorHash { get; set; }

		[JsonProperty("destinationHash")]
		public uint DestinationHash { get; set; }

		[JsonProperty("backgroundImagePath")]
		public string BackgroundImagePath { get; set; }
	}
}
