// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// All damage types that are possible in the game are defined here, along with localized info and icons as needed.
	/// </summary>
	public partial class DestinyDamageTypeDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("transparentIconPath")]
		public string TransparentIconPath { get; set; }

		[JsonProperty("showIcon")]
		public bool ShowIcon { get; set; }

		[JsonProperty("enumValue")]
		public Destiny.DamageType EnumValue { get; set; }

		[JsonProperty("hash")]
		public uint Hash { get; set; }

		[JsonProperty("index")]
		public int Index { get; set; }

		[JsonProperty("redacted")]
		public bool Redacted { get; set; }
	}
}
