//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Information about the item's calculated stats, with as much data as we can find for the stats without having an actual instance of the item.
	/// Note that this means the entire concept of providing these stats is fundamentally insufficient: we cannot predict with 100% accuracy the conditions under which an item can spawn, so we use various heuristics to attempt to simulate the conditions as accurately as possible. Actual stats for items in-game can and will vary, but these should at least be useful base points for comparison and display.
	/// It is also worth noting that some stats, like Magazine size, have further calculations performed on them by scripts in-game and on the game servers that BNet does not have access to. We cannot know how those stats are further transformed, and thus some stats will be inaccurate even on instances of items in BNet vs. how they appear in-game. This is a known limitation of our item statistics, without any planned fix.
	/// </summary>
	public partial class DestinyItemStatBlockDefinition
	{
		[JsonProperty("disablePrimaryStatDisplay")]
		public bool DisablePrimaryStatDisplay { get; set; }

		[JsonProperty("statGroupHash")]
		public uint? StatGroupHash { get; set; }

		[JsonProperty("stats")]
		public System.Collections.Generic.Dictionary<uint, Destiny.Definitions.DestinyInventoryItemStatDefinition> Stats { get; set; }

		[JsonProperty("hasDisplayableStats")]
		public bool HasDisplayableStats { get; set; }

		[JsonProperty("primaryBaseStatHash")]
		public uint PrimaryBaseStatHash { get; set; }
	}
}
