//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Data about an item's "sources": ways that the item can be obtained.
	/// </summary>
	public partial class DestinyItemSourceBlockDefinition
	{
		[JsonProperty("sourceHashes")]
		public uint[] SourceHashes { get; set; }

		[JsonProperty("sources")]
		public Destiny.Definitions.Sources.DestinyItemSourceDefinition[] Sources { get; set; }

		[JsonProperty("exclusive")]
		public BungieMembershipType Exclusive { get; set; }

		[JsonProperty("vendorSources")]
		public Destiny.Definitions.DestinyItemVendorSourceReference[] VendorSources { get; set; }
	}
}
