//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Describes the way that an Item Stat (see DestinyStatDefinition) is transformed using the DestinyStatGroupDefinition related to that item. See both of the aforementioned definitions for more information about the stages of stat transformation.
	/// This represents the transformation of a stat into a "Display" stat (the closest value that BNet can get to the in-game display value of the stat)
	/// </summary>
	public partial class DestinyStatDisplayDefinition
	{
		[JsonProperty("statHash")]
		public uint StatHash { get; set; }

		[JsonProperty("maximumValue")]
		public int MaximumValue { get; set; }

		[JsonProperty("displayAsNumeric")]
		public bool DisplayAsNumeric { get; set; }

		[JsonProperty("displayInterpolation")]
		public Interpolation.InterpolationPoint[] DisplayInterpolation { get; set; }
	}
}
