//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This definition represents an "Activity Mode" as it exists in the Historical Stats endpoints. An individual Activity Mode represents a collection of activities that are played in a certain way. For example, Nightfall Strikes are part of a "Nightfall" activity mode, and any activities played as the PVP mode "Clash" are part of the "Clash activity mode.
	/// Activity modes are nested under each other in a hierarchy, so that if you ask for - for example - "AllPvP", you will get any PVP activities that the user has played, regardless of what specific PVP mode was being played.
	/// </summary>
	public partial class DestinyActivityModeDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("pgcrImage")]
		public string PgcrImage { get; set; }

		[JsonProperty("modeType")]
		public Destiny.HistoricalStats.Definitions.DestinyActivityModeType ModeType { get; set; }

		[JsonProperty("activityModeCategory")]
		public Destiny.DestinyActivityModeCategory ActivityModeCategory { get; set; }

		[JsonProperty("isTeamBased")]
		public bool IsTeamBased { get; set; }

		[JsonProperty("isAggregateMode")]
		public bool IsAggregateMode { get; set; }

		[JsonProperty("parentHashes")]
		public uint[] ParentHashes { get; set; }

		[JsonProperty("friendlyName")]
		public string FriendlyName { get; set; }

		[JsonProperty("activityModeMappings")]
		public System.Collections.Generic.Dictionary<uint, Destiny.HistoricalStats.Definitions.DestinyActivityModeType> ActivityModeMappings { get; set; }

		[JsonProperty("display")]
		public bool Display { get; set; }

		[JsonProperty("order")]
		public int Order { get; set; }
	}
}
