// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.Definitions
{
	[Flags]
	public enum DestinyTalentNodeStepImpactEffects
	{
		None = 0x0,

		ArmorPiercing = 0x1,

		Ricochet = 0x2,

		Flinch = 0x4,

		CollateralDamage = 0x8,

		Disorient = 0x10,

		HighlightTarget = 0x20,

		All = 0x3F
	}
}
