//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// An artificial construct provided by Bungie.Net, where we attempt to group talent nodes by functionality.
	/// This is a single set of references to Talent Nodes that share a common trait or purpose.
	/// </summary>
	public partial class DestinyTalentNodeCategory
	{
		[JsonProperty("identifier")]
		public string Identifier { get; set; }

		[JsonProperty("isLoreDriven")]
		public bool IsLoreDriven { get; set; }

		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("nodeHashes")]
		public uint[] NodeHashes { get; set; }
	}
}
