//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Represent a set of material requirements: Items that either need to be owned or need to be consumed in order to perform an action.
	/// A variety of other entities refer to these as gatekeepers and payments for actions that can be performed in game.
	/// </summary>
	public partial class DestinyMaterialRequirementSetDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("materials")]
		public Destiny.Definitions.DestinyMaterialRequirement[] Materials { get; set; }
	}
}
