//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Defines an "Objective".
	/// An objective is a specific task you should accomplish in the game. These are referred to by:
	/// - Quest Steps (which are DestinyInventoryItemDefinition entities with Objectives)
	/// - Challenges (which are Objectives defined on an DestinyActivityDefintion)
	/// - Milestones (which refer to Objectives that are defined on both Quest Steps and Activities)
	/// - Anything else that the designers decide to do later.
	/// Objectives have progress, a notion of having been Completed, human readable data describing the task to be accomplished, and a lot of optional tack-on data that can enhance the information provided about the task.
	/// </summary>
	public partial class DestinyObjectiveDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("completionValue")]
		public int CompletionValue { get; set; }

		[JsonProperty("scope")]
		public Destiny.DestinyGatingScope Scope { get; set; }

		[JsonProperty("locationHash")]
		public uint LocationHash { get; set; }

		[JsonProperty("allowNegativeValue")]
		public bool AllowNegativeValue { get; set; }

		[JsonProperty("allowValueChangeWhenCompleted")]
		public bool AllowValueChangeWhenCompleted { get; set; }

		[JsonProperty("isCountingDownward")]
		public bool IsCountingDownward { get; set; }

		[JsonProperty("valueStyle")]
		public Destiny.DestinyUnlockValueUIStyle ValueStyle { get; set; }

		[JsonProperty("progressDescription")]
		public string ProgressDescription { get; set; }

		[JsonProperty("perks")]
		public Destiny.Definitions.DestinyObjectivePerkEntryDefinition Perks { get; set; }

		[JsonProperty("stats")]
		public Destiny.Definitions.DestinyObjectiveStatEntryDefinition Stats { get; set; }

		[JsonProperty("minimumVisibilityThreshold")]
		public int MinimumVisibilityThreshold { get; set; }

		[JsonProperty("allowOvercompletion")]
		public bool AllowOvercompletion { get; set; }

		[JsonProperty("showValueOnComplete")]
		public bool ShowValueOnComplete { get; set; }

		[JsonProperty("completedValueStyle")]
		public Destiny.DestinyUnlockValueUIStyle CompletedValueStyle { get; set; }

		[JsonProperty("inProgressValueStyle")]
		public Destiny.DestinyUnlockValueUIStyle InProgressValueStyle { get; set; }
	}
}
