//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Not terribly useful, some basic cooldown interaction info.
	/// </summary>
	public partial class DestinyVendorSaleItemActionBlockDefinition
	{
		[JsonProperty("executeSeconds")]
		public decimal ExecuteSeconds { get; set; }

		[JsonProperty("isPositive")]
		public bool IsPositive { get; set; }
	}
}
