// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// The definition information for a specific socket on an item. This will determine how the socket behaves in-game.
	/// </summary>
	public partial class DestinyItemSocketEntryDefinition
	{
		[JsonProperty("socketTypeHash")]
		public uint SocketTypeHash { get; set; }

		[JsonProperty("singleInitialItemHash")]
		public uint SingleInitialItemHash { get; set; }

		[JsonProperty("reusablePlugItems")]
		public Destiny.Definitions.DestinyItemSocketEntryPlugItemDefinition[] ReusablePlugItems { get; set; }

		[JsonProperty("preventInitializationOnVendorPurchase")]
		public bool PreventInitializationOnVendorPurchase { get; set; }

		[JsonProperty("hidePerksInItemTooltip")]
		public bool HidePerksInItemTooltip { get; set; }

		[JsonProperty("plugSources")]
		public Destiny.SocketPlugSources PlugSources { get; set; }

		[JsonProperty("reusablePlugSetHash")]
		public uint? ReusablePlugSetHash { get; set; }

		[JsonProperty("randomizedPlugItems")]
		public Destiny.Definitions.DestinyItemSocketEntryPlugItemRandomizedDefinition[] RandomizedPlugItems { get; set; }
	}
}
