// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// The definition for an "inventory flyout": a UI screen where we show you part of an otherwise hidden vendor inventory: like the Vault inventory buckets.
	/// </summary>
	public partial class DestinyVendorInventoryFlyoutDefinition
	{
		[JsonProperty("lockedDescription")]
		public string LockedDescription { get; set; }

		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("buckets")]
		public Destiny.Definitions.DestinyVendorInventoryFlyoutBucketDefinition[] Buckets { get; set; }

		[JsonProperty("flyoutId")]
		public uint FlyoutId { get; set; }

		[JsonProperty("suppressNewness")]
		public bool SuppressNewness { get; set; }

		[JsonProperty("equipmentSlotHash")]
		public uint? EquipmentSlotHash { get; set; }
	}
}
