//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.Definitions
{
	[Flags]
	public enum DestinyTalentNodeStepLightAbilities
	{
		None = 0x0,

		Grenades = 0x1,

		Melee = 0x2,

		MovementModes = 0x4,

		Orbs = 0x8,

		SuperEnergy = 0x10,

		SuperMods = 0x20,

		All = 0x3F
	}
}
