//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This defines a single Step in a progression (which roughly equates to a level. See DestinyProgressionDefinition for caveats).
	/// </summary>
	public partial class DestinyProgressionStepDefinition
	{
		[JsonProperty("stepName")]
		public string StepName { get; set; }

		[JsonProperty("displayEffectType")]
		public Destiny.DestinyProgressionStepDisplayEffect DisplayEffectType { get; set; }

		[JsonProperty("progressTotal")]
		public int ProgressTotal { get; set; }

		[JsonProperty("rewardItems")]
		public Destiny.DestinyItemQuantity[] RewardItems { get; set; }

		[JsonProperty("icon")]
		public string Icon { get; set; }
	}
}
