// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	public partial class DestinyActivityLoadoutRequirement
	{
		[JsonProperty("equipmentSlotHash")]
		public uint EquipmentSlotHash { get; set; }

		[JsonProperty("allowedEquippedItemHashes")]
		public uint[] AllowedEquippedItemHashes { get; set; }

		[JsonProperty("allowedWeaponSubTypes")]
		public Destiny.DestinyItemSubType[] AllowedWeaponSubTypes { get; set; }
	}
}
