// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Information about a single inventory bucket in a vendor flyout UI and how it is shown.
	/// </summary>
	public partial class DestinyVendorInventoryFlyoutBucketDefinition
	{
		[JsonProperty("collapsible")]
		public bool Collapsible { get; set; }

		[JsonProperty("inventoryBucketHash")]
		public uint InventoryBucketHash { get; set; }

		[JsonProperty("sortItemsBy")]
		public Destiny.DestinyItemSortType SortItemsBy { get; set; }
	}
}
