// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.Definitions
{
	[Flags]
	public enum DestinyTalentNodeStepGuardianAttributes
	{
		None = 0x0,

		Stats = 0x1,

		Shields = 0x2,

		Health = 0x4,

		Revive = 0x8,

		AimUnderFire = 0x10,

		Radar = 0x20,

		Invisibility = 0x40,

		Reputations = 0x80,

		All = 0xFF
	}
}
