//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This is a bit of an odd duck. Apparently, if talent nodes steps have this data, the game will go through on step activation and alter the first Socket it finds on the item that has a type matching the given socket type, inserting the indicated plug item.
	/// </summary>
	public partial class DestinyNodeSocketReplaceResponse
	{
		[JsonProperty("socketTypeHash")]
		public uint SocketTypeHash { get; set; }

		[JsonProperty("plugItemHash")]
		public uint PlugItemHash { get; set; }
	}
}
