// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This is a bit of an odd duck. Apparently, if talent nodes steps have this data, the game will go through on step activation and alter the first Socket it finds on the item that has a type matching the given socket type, inserting the indicated plug item.
	/// </summary>
	public partial class DestinyNodeSocketReplaceResponse
	{
		[JsonProperty("socketTypeHash")]
		public uint SocketTypeHash { get; set; }

		[JsonProperty("plugItemHash")]
		public uint PlugItemHash { get; set; }
	}
}
