//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Activities can refer to one or more sets of tooltip-friendly reward data. These are the definitions for those tooltip friendly rewards.
	/// </summary>
	public partial class DestinyActivityRewardDefinition
	{
		[JsonProperty("rewardText")]
		public string RewardText { get; set; }

		[JsonProperty("rewardItems")]
		public Destiny.DestinyItemQuantity[] RewardItems { get; set; }
	}
}
