//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// The static data about Activities in Destiny 2.
	/// Note that an Activity must be combined with an ActivityMode to know - from a Gameplay perspective - what the user is "Playing".
	/// In most PvE activities, this is fairly straightforward. A Story Activity can only be played in the Story Activity Mode.
	/// However, in PvP activities, the Activity alone only tells you the map being played, or the Playlist that the user chose to enter. You'll need to know the Activity Mode they're playing to know that they're playing Mode X on Map Y.
	/// Activity Definitions tell a great deal of information about what *could* be relevant to a user: what rewards they can earn, what challenges could be performed, what modifiers could be applied. To figure out which of these properties is actually live, you'll need to combine the definition with "Live" data from one of the Destiny endpoints.
	/// Activities also have Activity Types, but unfortunately in Destiny 2 these are even less reliable of a source of information than they were in Destiny 1. I will be looking into ways to provide more reliable sources for type information as time goes on, but for now we're going to have to deal with the limitations. See DestinyActivityTypeDefinition for more information.
	/// </summary>
	public partial class DestinyActivityDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("originalDisplayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition OriginalDisplayProperties { get; set; }

		[JsonProperty("selectionScreenDisplayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition SelectionScreenDisplayProperties { get; set; }

		[JsonProperty("releaseIcon")]
		public string ReleaseIcon { get; set; }

		[JsonProperty("releaseTime")]
		public int ReleaseTime { get; set; }

		[JsonProperty("activityLevel")]
		public int ActivityLevel { get; set; }

		[JsonProperty("activityLightLevel")]
		public int ActivityLightLevel { get; set; }

		[JsonProperty("destinationHash")]
		public uint DestinationHash { get; set; }

		[JsonProperty("placeHash")]
		public uint PlaceHash { get; set; }

		[JsonProperty("activityTypeHash")]
		public uint ActivityTypeHash { get; set; }

		[JsonProperty("tier")]
		public int Tier { get; set; }

		[JsonProperty("pgcrImage")]
		public string PgcrImage { get; set; }

		[JsonProperty("rewards")]
		public Destiny.Definitions.DestinyActivityRewardDefinition[] Rewards { get; set; }

		[JsonProperty("modifiers")]
		public Destiny.Definitions.DestinyActivityModifierReferenceDefinition[] Modifiers { get; set; }

		[JsonProperty("isPlaylist")]
		public bool IsPlaylist { get; set; }

		[JsonProperty("challenges")]
		public Destiny.Definitions.DestinyActivityChallengeDefinition[] Challenges { get; set; }

		[JsonProperty("optionalUnlockStrings")]
		public Destiny.Definitions.DestinyActivityUnlockStringDefinition[] OptionalUnlockStrings { get; set; }

		[JsonProperty("playlistItems")]
		public Destiny.Definitions.DestinyActivityPlaylistItemDefinition[] PlaylistItems { get; set; }

		[JsonProperty("activityGraphList")]
		public Destiny.Definitions.DestinyActivityGraphListEntryDefinition[] ActivityGraphList { get; set; }

		[JsonProperty("matchmaking")]
		public Destiny.Definitions.DestinyActivityMatchmakingBlockDefinition Matchmaking { get; set; }

		[JsonProperty("guidedGame")]
		public Destiny.Definitions.DestinyActivityGuidedBlockDefinition GuidedGame { get; set; }

		[JsonProperty("directActivityModeHash")]
		public uint? DirectActivityModeHash { get; set; }

		[JsonProperty("directActivityModeType")]
		public Destiny.HistoricalStats.Definitions.DestinyActivityModeType? DirectActivityModeType { get; set; }

		[JsonProperty("loadouts")]
		public Destiny.Definitions.DestinyActivityLoadoutRequirementSet[] Loadouts { get; set; }

		[JsonProperty("activityModeHashes")]
		public uint[] ActivityModeHashes { get; set; }

		[JsonProperty("activityModeTypes")]
		public Destiny.HistoricalStats.Definitions.DestinyActivityModeType[] ActivityModeTypes { get; set; }

		[JsonProperty("isPvP")]
		public bool IsPvP { get; set; }

		[JsonProperty("insertionPoints")]
		public Destiny.Definitions.DestinyActivityInsertionPointDefinition[] InsertionPoints { get; set; }

		[JsonProperty("activityLocationMappings")]
		public Destiny.Constants.DestinyEnvironmentLocationMapping[] ActivityLocationMappings { get; set; }
	}
}
