//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// On to one of the more confusing subjects of the API. What is a Destination, and what is the relationship between it, Activities, Locations, and Places?
	/// A "Destination" is a specific region/city/area of a larger "Place". For instance, a Place might be Earth where a Destination might be Bellevue, Washington. (Please, pick a more interesting destination if you come to visit Earth).
	/// </summary>
	public partial class DestinyDestinationDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("placeHash")]
		public uint PlaceHash { get; set; }

		[JsonProperty("defaultFreeroamActivityHash")]
		public uint DefaultFreeroamActivityHash { get; set; }

		[JsonProperty("activityGraphEntries")]
		public Destiny.Definitions.DestinyActivityGraphListEntryDefinition[] ActivityGraphEntries { get; set; }

		[JsonProperty("bubbleSettings")]
		public Destiny.Definitions.DestinyDestinationBubbleSettingDefinition[] BubbleSettings { get; set; }

		[JsonProperty("bubbles")]
		public Destiny.Definitions.DestinyBubbleDefinition[] Bubbles { get; set; }
	}
}
