// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This Block defines the rendering data associated with the item, if any.
	/// </summary>
	public partial class DestinyItemTranslationBlockDefinition
	{
		[JsonProperty("weaponPatternIdentifier")]
		public string WeaponPatternIdentifier { get; set; }

		[JsonProperty("weaponPatternHash")]
		public uint WeaponPatternHash { get; set; }

		[JsonProperty("defaultDyes")]
		public Destiny.DyeReference[] DefaultDyes { get; set; }

		[JsonProperty("lockedDyes")]
		public Destiny.DyeReference[] LockedDyes { get; set; }

		[JsonProperty("customDyes")]
		public Destiny.DyeReference[] CustomDyes { get; set; }

		[JsonProperty("arrangements")]
		public Destiny.Definitions.DestinyGearArtArrangementReference[] Arrangements { get; set; }

		[JsonProperty("hasGeometry")]
		public bool HasGeometry { get; set; }
	}
}
