// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Sockets are grouped into categories in the UI. These define which category and which sockets are under that category.
	/// </summary>
	public partial class DestinyItemSocketCategoryDefinition
	{
		[JsonProperty("socketCategoryHash")]
		public uint SocketCategoryHash { get; set; }

		[JsonProperty("socketIndexes")]
		public int[] SocketIndexes { get; set; }
	}
}
