// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	public partial class DestinyGearArtArrangementReference
	{
		[JsonProperty("classHash")]
		public uint ClassHash { get; set; }

		[JsonProperty("artArrangementHash")]
		public uint ArtArrangementHash { get; set; }
	}
}
