//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Defines the conditions under which stat modifications will be applied to a Character while participating in an objective.
	/// </summary>
	public partial class DestinyObjectiveStatEntryDefinition
	{
		[JsonProperty("stat")]
		public Destiny.Definitions.DestinyItemInvestmentStatDefinition Stat { get; set; }

		[JsonProperty("style")]
		public Destiny.DestinyObjectiveGrantStyle Style { get; set; }
	}
}
