// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// The information for how the vendor purchase should override a given socket with custom plug data.
	/// </summary>
	public partial class DestinyVendorItemSocketOverride
	{
		[JsonProperty("singleItemHash")]
		public uint? SingleItemHash { get; set; }

		[JsonProperty("randomizedOptionsCount")]
		public int RandomizedOptionsCount { get; set; }

		[JsonProperty("socketTypeHash")]
		public uint SocketTypeHash { get; set; }
	}
}
