//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Destinations and Activities may have default Activity Graphs that should be shown when you bring up the Director and are playing in either.
	/// This contract defines the graph referred to and the gating for when it is relevant.
	/// </summary>
	public partial class DestinyActivityGraphListEntryDefinition
	{
		[JsonProperty("activityGraphHash")]
		public uint ActivityGraphHash { get; set; }
	}
}
