//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.Definitions
{
	[Flags]
	public enum DestinyTalentNodeStepDamageTypes
	{
		None = 0x0,

		Kinetic = 0x1,

		Arc = 0x2,

		Solar = 0x4,

		Void = 0x8,

		All = 0xF
	}
}
