//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Information about matchmaking and party size for the activity.
	/// </summary>
	public partial class DestinyActivityMatchmakingBlockDefinition
	{
		[JsonProperty("isMatchmade")]
		public bool IsMatchmade { get; set; }

		[JsonProperty("minParty")]
		public int MinParty { get; set; }

		[JsonProperty("maxParty")]
		public int MaxParty { get; set; }

		[JsonProperty("maxPlayers")]
		public int MaxPlayers { get; set; }

		[JsonProperty("requiresGuardianOath")]
		public bool RequiresGuardianOath { get; set; }
	}
}
