//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// In addition to item quantity information for vendor prices, this also has any optional information that may exist about how the item's quantity can be modified. (unfortunately not information that is able to be read outside of the BNet servers, but it's there)
	/// </summary>
	public partial class DestinyVendorItemQuantity
	{
		[JsonProperty("itemHash")]
		public uint ItemHash { get; set; }

		[JsonProperty("itemInstanceId")]
		public long? ItemInstanceId { get; set; }

		[JsonProperty("quantity")]
		public int Quantity { get; set; }
	}
}
