// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Activities can refer to one or more sets of tooltip-friendly reward data. These are the definitions for those tooltip friendly rewards.
	/// </summary>
	public partial class DestinyActivityRewardDefinition
	{
		[JsonProperty("rewardText")]
		public string RewardText { get; set; }

		[JsonProperty("rewardItems")]
		public Destiny.DestinyItemQuantity[] RewardItems { get; set; }
	}
}
