// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// If defined, the item has at least one socket.
	/// </summary>
	public partial class DestinyItemSocketBlockDefinition
	{
		[JsonProperty("detail")]
		public string Detail { get; set; }

		[JsonProperty("socketEntries")]
		public Destiny.Definitions.DestinyItemSocketEntryDefinition[] SocketEntries { get; set; }

		[JsonProperty("intrinsicSockets")]
		public Destiny.Definitions.DestinyItemIntrinsicSocketEntryDefinition[] IntrinsicSockets { get; set; }

		[JsonProperty("socketCategories")]
		public Destiny.Definitions.DestinyItemSocketCategoryDefinition[] SocketCategories { get; set; }
	}
}
