// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Talent nodes have requirements that must be met before they can be activated.
	/// This describes the material costs, the Level of the Talent Grid's progression required, and other conditional information that limits whether a talent node can be activated.
	/// </summary>
	public partial class DestinyNodeActivationRequirement
	{
		[JsonProperty("gridLevel")]
		public int GridLevel { get; set; }

		[JsonProperty("materialRequirementHashes")]
		public uint[] MaterialRequirementHashes { get; set; }
	}
}
