// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// An overly complicated wrapper for the item level at which the item should spawn.
	/// </summary>
	public partial class DestinyItemCreationEntryLevelDefinition
	{
		[JsonProperty("level")]
		public int Level { get; set; }
	}
}
