//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Primarily for Quests, this is the definition of properties related to the item if it is a quest and its various quest steps.
	/// </summary>
	public partial class DestinyItemSetBlockDefinition
	{
		[JsonProperty("itemList")]
		public Destiny.Definitions.DestinyItemSetBlockEntryDefinition[] ItemList { get; set; }

		[JsonProperty("requireOrderedSetItemAdd")]
		public bool RequireOrderedSetItemAdd { get; set; }

		[JsonProperty("setIsFeatured")]
		public bool SetIsFeatured { get; set; }

		[JsonProperty("setType")]
		public string SetType { get; set; }
	}
}
