//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// A Vendor Interaction is a dialog shown by the vendor other than sale items or transfer screens. The vendor is showing you something, and asking you to reply to it by choosing an option or reward.
	/// </summary>
	public partial class DestinyVendorInteractionDefinition
	{
		[JsonProperty("interactionIndex")]
		public int InteractionIndex { get; set; }

		[JsonProperty("replies")]
		public Destiny.Definitions.DestinyVendorInteractionReplyDefinition[] Replies { get; set; }

		[JsonProperty("vendorCategoryIndex")]
		public int VendorCategoryIndex { get; set; }

		[JsonProperty("questlineItemHash")]
		public uint QuestlineItemHash { get; set; }

		[JsonProperty("sackInteractionList")]
		public Destiny.Definitions.DestinyVendorInteractionSackEntryDefinition[] SackInteractionList { get; set; }

		[JsonProperty("uiInteractionType")]
		public uint UIInteractionType { get; set; }

		[JsonProperty("interactionType")]
		public Destiny.VendorInteractionType InteractionType { get; set; }

		[JsonProperty("rewardBlockLabel")]
		public string RewardBlockLabel { get; set; }

		[JsonProperty("rewardVendorCategoryIndex")]
		public int RewardVendorCategoryIndex { get; set; }

		[JsonProperty("flavorLineOne")]
		public string FlavorLineOne { get; set; }

		[JsonProperty("flavorLineTwo")]
		public string FlavorLineTwo { get; set; }

		[JsonProperty("headerDisplayProperties")]
		public Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition HeaderDisplayProperties { get; set; }

		[JsonProperty("instructions")]
		public string Instructions { get; set; }
	}
}
