//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// Items that can be equipped define this block. It contains information we need to understand how and when the item can be equipped.
	/// </summary>
	public partial class DestinyEquippingBlockDefinition
	{
		[JsonProperty("gearsetItemHash")]
		public uint? GearsetItemHash { get; set; }

		[JsonProperty("uniqueLabel")]
		public string UniqueLabel { get; set; }

		[JsonProperty("uniqueLabelHash")]
		public uint UniqueLabelHash { get; set; }

		[JsonProperty("equipmentSlotTypeHash")]
		public uint EquipmentSlotTypeHash { get; set; }

		[JsonProperty("attributes")]
		public Destiny.EquippingItemBlockAttributes Attributes { get; set; }

		[JsonProperty("ammoType")]
		public Destiny.DestinyAmmunitionType AmmoType { get; set; }

		[JsonProperty("displayStrings")]
		public string[] DisplayStrings { get; set; }
	}
}
