//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// This defines an item's "Value". Unfortunately, this appears to be used in different ways depending on the way that the item itself is used.
	/// For items being sold at a Vendor, this is the default "sale price" of the item. These days, the vendor itself almost always sets the price, but it still possible for the price to fall back to this value. For quests, it is a preview of rewards you can gain by completing the quest. For dummy items, if the itemValue refers to an Emblem, it is the emblem that should be shown as the reward. (jeez louise)
	/// It will likely be used in a number of other ways in the future, it appears to be a bucket where they put arbitrary items and quantities into the item.
	/// </summary>
	public partial class DestinyItemValueBlockDefinition
	{
		[JsonProperty("itemValue")]
		public Destiny.DestinyItemQuantity[] ItemValue { get; set; }

		[JsonProperty("valueDescription")]
		public string ValueDescription { get; set; }
	}
}
