//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// If an item can have an action performed on it (like "Dismantle"), it will be defined here if you care.
	/// </summary>
	public partial class DestinyItemCraftingBlockDefinition
	{
		[JsonProperty("outputItemHash")]
		public uint OutputItemHash { get; set; }

		[JsonProperty("requiredSocketTypeHashes")]
		public uint[] RequiredSocketTypeHashes { get; set; }

		[JsonProperty("failedRequirementStrings")]
		public string[] FailedRequirementStrings { get; set; }

		[JsonProperty("baseMaterialRequirements")]
		public uint? BaseMaterialRequirements { get; set; }

		[JsonProperty("bonusPlugs")]
		public Destiny.Definitions.DestinyItemCraftingBlockBonusPlugDefinition[] BonusPlugs { get; set; }
	}
}
