//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// A "Progression" in Destiny is best explained by an example.
	/// A Character's "Level" is a progression: it has Experience that can be earned, levels that can be gained, and is evaluated and displayed at various points in the game. A Character's "Faction Reputation" is also a progression for much the same reason.
	/// Progression is used by a variety of systems, and the definition of a Progression will generally only be useful if combining with live data (such as a character's DestinyCharacterProgressionComponent.progressions property, which holds that character's live Progression states).
	/// Fundamentally, a Progression measures your "Level" by evaluating the thresholds in its Steps (one step per level, except for the last step which can be repeated indefinitely for "Levels" that have no ceiling) against the total earned "progression points"/experience. (for simplicity purposes, we will henceforth refer to earned progression points as experience, though it need not be a mechanic that in any way resembles Experience in a traditional sense).
	/// Earned experience is calculated in a variety of ways, determined by the Progression's scope. These go from looking up a stored value to performing exceedingly obtuse calculations. This is why we provide live data in DestinyCharacterProgressionComponent.progressions, so you don't have to worry about those.
	/// </summary>
	public partial class DestinyProgressionDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("displayProperties")]
		public Destiny.Definitions.DestinyProgressionDisplayPropertiesDefinition DisplayProperties { get; set; }

		[JsonProperty("scope")]
		public Destiny.DestinyProgressionScope Scope { get; set; }

		[JsonProperty("repeatLastStep")]
		public bool RepeatLastStep { get; set; }

		[JsonProperty("source")]
		public string Source { get; set; }

		[JsonProperty("steps")]
		public Destiny.Definitions.DestinyProgressionStepDefinition[] Steps { get; set; }

		[JsonProperty("visible")]
		public bool Visible { get; set; }

		[JsonProperty("factionHash")]
		public uint? FactionHash { get; set; }

		[JsonProperty("color")]
		public Destiny.Misc.DestinyColor Color { get; set; }

		[JsonProperty("rankIcon")]
		public string RankIcon { get; set; }

		[JsonProperty("rewardItems")]
		public Destiny.Definitions.DestinyProgressionRewardItemQuantity[] RewardItems { get; set; }
	}
}
