//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions
{
	/// <summary>
	/// The results of a search for Destiny content. This will be improved on over time, I've been doing some experimenting to see what might be useful.
	/// </summary>
	public partial class DestinyEntitySearchResult
	{
		[JsonProperty("suggestedWords")]
		public string[] SuggestedWords { get; set; }

		[JsonProperty("results")]
		public SearchResultOfDestinyEntitySearchResultItem Results { get; set; }
	}
}
