// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Animations
{
	public partial class DestinyAnimationReference
	{
		[JsonProperty("animName")]
		public string AnimName { get; set; }

		[JsonProperty("animIdentifier")]
		public string AnimIdentifier { get; set; }

		[JsonProperty("path")]
		public string Path { get; set; }
	}
}
