// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Ignores
{
	public enum IgnoreLength
	{
		None = 0,

		Week = 1,

		TwoWeeks = 2,

		ThreeWeeks = 3,

		Month = 4,

		ThreeMonths = 5,

		SixMonths = 6,

		Year = 7,

		Forever = 8,

		ThreeMinutes = 9,

		Hour = 10,

		ThirtyDays = 11
	}
}
