//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Ignores
{
	public partial class IgnoreResponse
	{
		[JsonProperty("isIgnored")]
		public bool IsIgnored { get; set; }

		[JsonProperty("ignoreFlags")]
		public Ignores.IgnoreStatus IgnoreFlags { get; set; }
	}
}
