//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Interpolation
{
	public partial class InterpolationPointFloat
	{
		[JsonProperty("value")]
		public decimal Value { get; set; }

		[JsonProperty("weight")]
		public decimal Weight { get; set; }
	}
}
