// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Interpolation
{
	public partial class InterpolationPoint
	{
		[JsonProperty("value")]
		public int Value { get; set; }

		[JsonProperty("weight")]
		public int Weight { get; set; }
	}
}
