//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.User.Models
{
	public partial class GetCredentialTypesForAccountResponse
	{
		[JsonProperty("credentialType")]
		public BungieCredentialType CredentialType { get; set; }

		[JsonProperty("credentialDisplayName")]
		public string CredentialDisplayName { get; set; }

		[JsonProperty("isPublic")]
		public bool IsPublic { get; set; }

		[JsonProperty("credentialAsString")]
		public string CredentialAsString { get; set; }
	}
}
