//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Character
{
	/// <summary>
	/// A minimal view of a character's equipped items, for the purpose of rendering a summary screen or showing the character in 3D.
	/// </summary>
	public partial class DestinyCharacterPeerView
	{
		[JsonProperty("equipment")]
		public Destiny.Character.DestinyItemPeerView[] Equipment { get; set; }
	}
}
