// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content
{
	public partial class CommentSummary
	{
		[JsonProperty("topicId")]
		public long TopicId { get; set; }

		[JsonProperty("commentCount")]
		public int CommentCount { get; set; }
	}
}
