//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Content
{
	public partial class NewsArticleRssResponse
	{
		[JsonProperty("NewsArticles")]
		public Content.NewsArticleRssItem[] NewsArticles { get; set; }

		[JsonProperty("CurrentPaginationToken")]
		public int CurrentPaginationToken { get; set; }

		[JsonProperty("NextPaginationToken")]
		public int? NextPaginationToken { get; set; }

		[JsonProperty("ResultCountThisPage")]
		public int ResultCountThisPage { get; set; }

		[JsonProperty("CategoryFilter")]
		public string CategoryFilter { get; set; }
	}
}
