//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingDetail
	{
		[JsonProperty("identifier")]
		public string Identifier { get; set; }

		[JsonProperty("entityType")]
		public Trending.TrendingEntryType EntityType { get; set; }

		[JsonProperty("news")]
		public Trending.TrendingEntryNews News { get; set; }

		[JsonProperty("support")]
		public Trending.TrendingEntrySupportArticle Support { get; set; }

		[JsonProperty("destinyItem")]
		public Trending.TrendingEntryDestinyItem DestinyItem { get; set; }

		[JsonProperty("destinyActivity")]
		public Trending.TrendingEntryDestinyActivity DestinyActivity { get; set; }

		[JsonProperty("destinyRitual")]
		public Trending.TrendingEntryDestinyRitual DestinyRitual { get; set; }

		[JsonProperty("creation")]
		public Trending.TrendingEntryCommunityCreation Creation { get; set; }
	}
}
