// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingEntryCommunityStream
	{
		[JsonProperty("image")]
		public string Image { get; set; }

		[JsonProperty("title")]
		public string Title { get; set; }

		[JsonProperty("partnershipIdentifier")]
		public string PartnershipIdentifier { get; set; }

		[JsonProperty("partnershipType")]
		public Partnerships.PartnershipType PartnershipType { get; set; }
	}
}
