// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingCategories
	{
		[JsonProperty("categories")]
		public Trending.TrendingCategory[] Categories { get; set; }
	}
}
