//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingEntryDestinyRitual
	{
		[JsonProperty("image")]
		public string Image { get; set; }

		[JsonProperty("icon")]
		public string Icon { get; set; }

		[JsonProperty("title")]
		public string Title { get; set; }

		[JsonProperty("subtitle")]
		public string Subtitle { get; set; }

		[JsonProperty("dateStart")]
		public DateTime? DateStart { get; set; }

		[JsonProperty("dateEnd")]
		public DateTime? DateEnd { get; set; }

		[JsonProperty("milestoneDetails")]
		public Destiny.Milestones.DestinyPublicMilestone MilestoneDetails { get; set; }

		[JsonProperty("eventContent")]
		public Destiny.Milestones.DestinyMilestoneContent EventContent { get; set; }
	}
}
