// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingCategory
	{
		[JsonProperty("categoryName")]
		public string CategoryName { get; set; }

		[JsonProperty("entries")]
		public SearchResultOfTrendingEntry Entries { get; set; }

		[JsonProperty("categoryId")]
		public string CategoryId { get; set; }
	}
}
