//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Trending
{
	public partial class TrendingEntryCommunityStream
	{
		[JsonProperty("image")]
		public string Image { get; set; }

		[JsonProperty("title")]
		public string Title { get; set; }

		[JsonProperty("partnershipIdentifier")]
		public string PartnershipIdentifier { get; set; }

		[JsonProperty("partnershipType")]
		public Partnerships.PartnershipType PartnershipType { get; set; }
	}
}
