// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet
{
	public partial class CoreIdentifierOfuint32
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("identifier")]
		public uint Identifier { get; set; }
	}
}
