//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet
{
	public partial class DestinyItemComponentSetOfint32
	{
		[JsonProperty("instances")]
		public DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent Instances { get; set; }

		[JsonProperty("perks")]
		public DictionaryComponentResponseOfint32AndDestinyItemPerksComponent Perks { get; set; }

		[JsonProperty("renderData")]
		public DictionaryComponentResponseOfint32AndDestinyItemRenderComponent RenderData { get; set; }

		[JsonProperty("stats")]
		public DictionaryComponentResponseOfint32AndDestinyItemStatsComponent Stats { get; set; }

		[JsonProperty("sockets")]
		public DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent Sockets { get; set; }

		[JsonProperty("talentGrids")]
		public DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent TalentGrids { get; set; }

		[JsonProperty("plugStates")]
		public DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent PlugStates { get; set; }

		[JsonProperty("objectives")]
		public DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent Objectives { get; set; }
	}
}
