// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet
{
	public partial class DestinyBaseItemComponentSetOfint64
	{
		[JsonProperty("objectives")]
		public DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent Objectives { get; set; }
	}
}
