//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet
{
	public enum GlobalAlertLevel
	{
		Unknown = 0,

		Blue = 1,

		Yellow = 2,

		Red = 3
	}
}
