// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet
{
	public partial class StreamInfo
	{
		[JsonProperty("ChannelName")]
		public string ChannelName { get; set; }
	}
}
