//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Traits
{
	public partial class DestinyTraitCategoryDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("traitCategoryId")]
		public string TraitCategoryId { get; set; }

		[JsonProperty("traitHashes")]
		public uint[] TraitHashes { get; set; }

		[JsonProperty("traitIds")]
		public string[] TraitIds { get; set; }
	}
}
