// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Advanced
{
	public partial class AwaAuthorizationResult
	{
		[JsonProperty("userSelection")]
		public Destiny.Advanced.AwaUserSelection UserSelection { get; set; }

		[JsonProperty("responseReason")]
		public Destiny.Advanced.AwaResponseReason ResponseReason { get; set; }

		[JsonProperty("developerNote")]
		public string DeveloperNote { get; set; }

		[JsonProperty("actionToken")]
		public string ActionToken { get; set; }

		[JsonProperty("maximumNumberOfUses")]
		public int MaximumNumberOfUses { get; set; }

		[JsonProperty("validUntil")]
		public DateTime? ValidUntil { get; set; }

		[JsonProperty("type")]
		public Destiny.Advanced.AwaType Type { get; set; }

		[JsonProperty("membershipType")]
		public BungieMembershipType MembershipType { get; set; }
	}
}
