// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny.Advanced
{
	public enum AwaType
	{
		None = 0,

		/// <summary>
		/// Insert plugs into sockets.
		/// </summary>
		InsertPlugs = 1
	}
}
