//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Items
{
	public partial class DestinyItemTierTypeInfusionBlock
	{
		[JsonProperty("baseQualityTransferRatio")]
		public decimal BaseQualityTransferRatio { get; set; }

		[JsonProperty("minimumQualityIncrement")]
		public int MinimumQualityIncrement { get; set; }
	}
}
