// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Presentation
{
	public partial class DestinyPresentationChildBlock
	{
		[JsonProperty("presentationNodeType")]
		public Destiny.DestinyPresentationNodeType PresentationNodeType { get; set; }

		[JsonProperty("parentPresentationNodeHashes")]
		public uint[] ParentPresentationNodeHashes { get; set; }

		[JsonProperty("displayStyle")]
		public Destiny.DestinyPresentationDisplayStyle DisplayStyle { get; set; }
	}
}
