//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Presentation
{
	/// <summary>
	/// This is the base class for all presentation system children. Presentation Nodes, Records, Collectibles, and Metrics.
	/// </summary>
	public partial class DestinyPresentationNodeBaseDefinition : Destiny.Definitions.DestinyDefinition
	{
		[JsonProperty("presentationNodeType")]
		public Destiny.DestinyPresentationNodeType PresentationNodeType { get; set; }

		[JsonProperty("traitIds")]
		public string[] TraitIds { get; set; }

		[JsonProperty("traitHashes")]
		public uint[] TraitHashes { get; set; }

		[JsonProperty("parentNodeHashes")]
		public uint[] ParentNodeHashes { get; set; }
	}
}
