// -----------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.  Any changes may be lost.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Presentation
{
	public partial class DestinyPresentationNodeRecordChildEntry
	{
		[JsonProperty("recordHash")]
		public uint RecordHash { get; set; }
	}
}
