//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace BungieNet.Destiny.Definitions.Presentation
{
	public partial class DestinyPresentationNodeChildEntry
	{
		[JsonProperty("presentationNodeHash")]
		public uint PresentationNodeHash { get; set; }
	}
}
